import {ApiError,message,login} from '../../services/api';
import {orderingRequest,mealNames} from '../../services/cart';
import {Review,Invitation,beijing} from '../../services/reviews';
Page({data:{loggedIn:false,busy:false,loading:false,error:'',state:'invitations',dishId:0,averageText:'暂无评分',reviewCount:0,page:1,hasMore:false,reviews:[] as (Review&{timeText:string})[],invitations:[] as (Invitation&{mealName:string;deadlineText:string})[]},_visible:false,_generation:0,
 onLoad(options:Record<string,string>){this.setData({dishId:Number(options.dishId)||0,state:options.dishId?'dish':'invitations'});},async onShow(){this._visible=true;this.setData({loggedIn:!!wx.getStorageSync('sessionToken')});if(this.data.loggedIn)await this.load();},onHide(){this._visible=false;this._generation++;this.setData({loading:false});},onUnload(){this.onHide();},
 async signIn(){this.setData({busy:true,error:''});try{await login();this.setData({loggedIn:true});await this.load();}catch(e){this.setData({error:message(e)});}finally{this.setData({busy:false});}},
 async load(){if(this.data.loading)return;const generation=++this._generation;this.setData({loading:true,error:''});try{const base=this.data.dishId?`/dishes/${this.data.dishId}/reviews`:this.data.state==='invitations'?'/my/review-invitations':'/my/reviews';const result=await orderingRequest<{reviews?:Review[];invitations?:Invitation[];average?:number|null;reviewCount?:number;page:number;hasMore:boolean}>(base+'?page='+this.data.page);if(!this._visible||generation!==this._generation)return;this.setData({averageText:result.average==null?'暂无评分':result.average.toFixed(1),reviewCount:result.reviewCount||0,hasMore:result.hasMore,reviews:(result.reviews||[]).map(r=>({...r,timeText:beijing(r.firstSubmittedAt)})),invitations:(result.invitations||[]).map(i=>({...i,mealName:mealNames[i.meal],deadlineText:beijing(i.deadline)}))});}catch(e){if(generation===this._generation){if(e instanceof ApiError&&e.code==='AUTH_REQUIRED')this.setData({loggedIn:false,reviews:[],invitations:[]});this.setData({error:message(e)});}}finally{if(generation===this._generation)this.setData({loading:false});}},
 tab(e:WechatMiniprogram.TouchEvent){if(this.data.loading)return;this.setData({state:e.currentTarget.dataset.state,page:1});void this.load();},next(){if(!this.data.loading){this.setData({page:this.data.page+1});void this.load();}},previous(){if(!this.data.loading&&this.data.page>1){this.setData({page:this.data.page-1});void this.load();}},open(e:WechatMiniprogram.TouchEvent){wx.navigateTo({url:`/subpackages/reviews/sheet?id=${e.currentTarget.dataset.id}`});}
});
