import {ApiError,login,message} from '../../services/api';
import {orderingRequest,mealNames} from '../../services/cart';
import {key,confirm} from '../../services/menu';
import {Sheet,Food,Share,beijing} from '../../services/reviews';
interface Attempt {path:string;method:'POST'|'PUT';body:object;key:string}
Page({data:{id:0,token:'',loggedIn:false,loading:false,busy:false,error:'',retryPending:false,sheet:null as Sheet|null,foods:[] as (Food&{averageText:string})[],mealName:'',deadlineText:'',canShare:false,shareError:'',editor:null as Food|null,rating:0,comment:'',stars:[1,2,3,4,5]},
 _visible:false,_generation:0,_attempt:null as Attempt|null,_editorVersion:null as number|null,_shareToken:'',_expiresLocal:0,_timer:0,
 onLoad(options:Record<string,string>){this.setData({id:Number(options.id)||0,token:options.token||''});},
 async onShow(){this._visible=true;wx.hideShareMenu();this.setData({loggedIn:!!wx.getStorageSync('sessionToken')});if(this.data.loggedIn)await this.load();},
 onHide(){this._visible=false;this._generation++;if(this._timer)clearTimeout(this._timer);},onUnload(){this.onHide();},
 async signIn(){if(this.data.busy)return;this.setData({busy:true,error:''});try{await login();this.setData({loggedIn:true});await this.load();}catch(e){this.setData({error:message(e)});}finally{this.setData({busy:false});}},
 base(){return this.data.token?`/review-invitations/${encodeURIComponent(this.data.token)}`:`/meal-orders/${this.data.id}/review-sheet`;},
 async load(){const generation=++this._generation;this.setData({loading:true});try{const sheet=await orderingRequest<Sheet>(this.base());if(!this._visible||generation!==this._generation)return;this.setData({sheet,foods:sheet.foods.map(f=>({...f,averageText:f.average===null?'暂无评分':f.average.toFixed(1)})),mealName:mealNames[sheet.meal],deadlineText:beijing(sheet.deadline)});this._expiresLocal=Date.now()+Date.parse(sheet.deadline)-Date.parse(sheet.serverTime);if(this._timer)clearTimeout(this._timer);if(sheet.canSubmit){this._timer=setTimeout(()=>{this.setData({canShare:false});wx.hideShareMenu();},Math.max(1,this._expiresLocal-Date.now()));await this.prepareShare();}else{this.setData({canShare:false});wx.hideShareMenu();}}catch(e){if(generation===this._generation){if(e instanceof ApiError&&e.code==='AUTH_REQUIRED')this.setData({loggedIn:false});this.setData({error:message(e),canShare:false});wx.hideShareMenu();}}finally{if(generation===this._generation)this.setData({loading:false});}},
 async prepareShare(){if(!this.data.sheet?.canSubmit)return;try{if(!this._shareToken){const result=await orderingRequest<Share>(`/meal-orders/${this.data.sheet.orderId}/review-shares`,'POST');this._shareToken=result.token;}if(!this._visible)return;this.setData({canShare:Date.now()<this._expiresLocal,shareError:''});if(this.data.canShare)wx.showShareMenu({menus:['shareAppMessage']});}catch(e){this.setData({shareError:'分享暂不可用，可重试准备分享',canShare:false});}},
 onShareAppMessage(){return this.data.canShare&&this._shareToken&&Date.now()<this._expiresLocal?{title:'这顿饭，来一起打个分',path:`/subpackages/reviews/sheet?token=${encodeURIComponent(this._shareToken)}`,imageUrl:'/assets/review-share.png'}:{title:'我们的餐桌',path:'/pages/mine/index',imageUrl:'/assets/review-share.png'};},
 edit(e:WechatMiniprogram.TouchEvent){if(this.data.busy||this._attempt)return;const food=this.data.sheet?.foods.find(f=>f.dishId===Number(e.currentTarget.dataset.id));if(!food||!this.data.sheet?.canSubmit||(food.mine&&!food.mine.canModify))return;this._editorVersion=food.mine?.version??null;this.setData({editor:food,rating:food.mine?.rating||0,comment:food.mine?.comment||'',error:''});},
 rate(e:WechatMiniprogram.TouchEvent){if(!this.data.busy&&!this._attempt)this.setData({rating:Number(e.currentTarget.dataset.star)});},text(e:WechatMiniprogram.Input){if(!this.data.busy&&!this._attempt)this.setData({comment:e.detail.value});},
 close(){if(!this.data.busy&&!this._attempt)this.setData({editor:null});},
 async submit(){if(this.data.busy||this._attempt||!this.data.editor)return;if(this.data.rating<1||this.data.rating>5){this.setData({error:'请先选择1—5星，没有默认评分'});return;}const food=this.data.editor;const modifying=this._editorVersion!==null;if(modifying&&!await confirm('每条评价只可修改一次，确认保存当前评分与文字？'))return;const path=modifying?`/reviews/${food.mine!.id}`:(this.data.token?`/review-invitations/${encodeURIComponent(this.data.token)}/reviews`:`/meal-orders/${this.data.sheet!.orderId}/reviews`);await this.perform({path,method:modifying?'PUT':'POST',body:modifying?{version:this._editorVersion,rating:this.data.rating,comment:this.data.comment}:{dishId:food.dishId,rating:this.data.rating,comment:this.data.comment},key:key()});},
 async retry(){if(this.data.busy||!this._attempt)return;if(!wx.getStorageSync('sessionToken')){await this.signIn();if(!this.data.loggedIn)return;}await this.perform(this._attempt);},
 async perform(attempt:Attempt){this._attempt=attempt;this.setData({busy:true,error:''});try{await orderingRequest(attempt.path,attempt.method,attempt.body,{'Idempotency-Key':attempt.key});this._attempt=null;this.setData({retryPending:false,editor:null});await this.load();wx.showToast({title:'评价已保存',icon:'success'});}catch(e){const uncertain=e instanceof ApiError&&['NETWORK_ERROR','SERVICE_UNAVAILABLE','AUTH_REQUIRED'].includes(e.code);if(!uncertain)this._attempt=null;this.setData({error:message(e),retryPending:uncertain});if(!uncertain)await this.load();}finally{this.setData({busy:false});}},
 async checkLatest(){if(this._attempt||this.data.busy||!this.data.editor)return;await this.load();const food=this.data.sheet?.foods.find(f=>f.dishId===this.data.editor!.dishId);if(!food?.mine?.canModify){this.setData({error:'最新评价已锁定，只能查看；当前输入仍保留。'});return;}if(await confirm(`最新评分${food.mine.rating}星，文字：${food.mine.comment||'无'}。保留当前输入，核对后再保存？`)){this._editorVersion=food.mine.version;this.setData({editor:food});}},noop(){}
});
