import {Me,request,ApiError,dailyGuard,message} from '../../services/api';
import {partyRequest,Create,Party,Attempt,uncertain,time,partyCovers,coverImage} from '../../services/party';
import {key,confirm} from '../../services/menu';
Page({data:{ready:false,busy:false,error:'',retryPending:false,theme:'',location:'',startDate:'',startTime:'18:00',endDate:'',endTime:'22:00',coverPreset:'DEFAULT',coverImage:coverImage('DEFAULT'),covers:partyCovers},_attempt:null as Attempt|null,_user:0,_visible:false,
 onLoad(){const date=new Date(Date.now()+8*3600000+86400000).toISOString().slice(0,10);this.setData({startDate:date,endDate:date});},
 async onShow(){this._visible=true;const me=await dailyGuard();if(!me||!this._visible)return;this._user=me.user.id;this.setData({ready:true});const saved=wx.getStorageSync<{user:number;attempt:Attempt}>('partyCreatePending');if(saved&&saved.user===this._user){this._attempt=saved.attempt;const f=saved.attempt.body as Create;this.setData({coverPreset:f.coverPreset||'DEFAULT',coverImage:coverImage(f.coverPreset),theme:f.theme,location:f.location,startDate:f.startAt.slice(0,10),startTime:f.startAt.slice(11,16),endDate:f.plannedEndAt.slice(0,10),endTime:f.plannedEndAt.slice(11,16),retryPending:true});}},onHide(){this._visible=false;},onUnload(){this.onHide();},
 input(e:WechatMiniprogram.CustomEvent<{value:string}>){if(!this.data.busy&&!this._attempt)this.setData({[e.currentTarget.dataset.field]:e.detail.value});},
 cover(e:WechatMiniprogram.TouchEvent){if(this.data.busy||this._attempt)return;const code=e.currentTarget.dataset.code as string;if(partyCovers.some(c=>c.code===code))this.setData({coverPreset:code,coverImage:coverImage(code)});},
 coverError(){this.setData({coverImage:coverImage('DEFAULT')});},
 async submit(){if(this.data.busy)return;if(this._attempt){await this.send();return;}try{const f:Create={theme:this.data.theme.trim(),location:this.data.location.trim(),startAt:time(this.data.startDate,this.data.startTime),plannedEndAt:time(this.data.endDate,this.data.endTime),longDurationConfirmed:false,coverPreset:this.data.coverPreset};if(!f.theme||!f.location)throw new Error('请填写主题和地点');if(Date.parse(f.plannedEndAt)<=Date.parse(f.startAt))throw new Error('结束必须晚于开始');if(Date.parse(f.plannedEndAt)-Date.parse(f.startAt)>7*86400000){if(!await confirm('这次聚会持续超过7天，确认使用当前起止时间？'))return;f.longDurationConfirmed=true;}this._attempt={path:'/parties',method:'POST',body:f,key:key()};await this.send();}catch(e){this.setData({error:message(e)});}},
 async send(){if(this.data.busy||!this._attempt)return;const me=await dailyGuard();if(!me)return;if(me.user.id!==this._user){this.setData({error:'登录账号已变化，请返回聚会列表后重试，原账号待核对创建仍保留。'});return;}this.setData({busy:true,error:''});const attempt=this._attempt;wx.setStorageSync('partyCreatePending',{user:this._user,attempt});try{const p=await partyRequest<Party>(attempt.path,attempt.method,attempt.body,{'Idempotency-Key':attempt.key});wx.removeStorageSync('partyCreatePending');this._attempt=null;this.setData({retryPending:false});if(this._visible)wx.redirectTo({url:`/subpackages/party/detail?id=${p.id}`});}catch(e){const pending=uncertain(e);if(!pending){wx.removeStorageSync('partyCreatePending');this._attempt=null;}this.setData({retryPending:pending,error:message(e)});}finally{this.setData({busy:false});}}
});
