import {ApiError,login,message,request,Me} from '../../services/api';
import {partyRequest,Party,Attempt,uncertain,coverImage} from '../../services/party';
import {key,confirm} from '../../services/menu';
import {beijing} from '../../services/reviews';
Page({data:{id:0,token:'',loggedIn:false,loading:false,busy:false,error:'',retryPending:false,party:null as Party|null,startText:'',endText:'',firstEndText:'',statusText:'',canShare:false,shareError:'',coverImage:coverImage('DEFAULT')},_visible:false,_generation:0,_attempt:null as Attempt|null,_shareToken:'',_loadedUser:0,_attemptUser:0,
 onLoad(o:Record<string,string>){this.setData({id:/^[1-9]\d{0,16}$/.test(o.id||'')?Number(o.id):0,token:o.token||''});},async onShow(){this._visible=true;wx.hideShareMenu();this.setData({loggedIn:!!wx.getStorageSync('sessionToken'),canShare:false});if(this.data.loggedIn)await this.load();},onHide(){this._visible=false;this._generation++;this._shareToken='';this.setData({canShare:false,loading:false});},onUnload(){this.onHide();},
 async signIn(){if(this.data.busy)return;this.setData({busy:true,error:''});try{await login();this.setData({loggedIn:true});await this.load();}catch(e){this.setData({error:message(e)});}finally{this.setData({busy:false});}},
 async load(){const g=++this._generation;this._shareToken='';this.setData({loading:true,error:'',party:null,canShare:false});wx.hideShareMenu();try{const p=await partyRequest<Party>(this.data.id?`/parties/${this.data.id}`:`/party-invitations/${encodeURIComponent(this.data.token)}`);if(!this._visible||g!==this._generation)return;if(this._loadedUser && this._loadedUser!==p.userId){this._attempt=null;this.setData({retryPending:false});}this._loadedUser=p.userId;const saved=wx.getStorageSync<{userId:number;attempt:Attempt}>(this.pendingKey(p.id,p.userId));if(saved?.userId===p.userId){this._attempt=saved.attempt;this._attemptUser=p.userId;this.setData({retryPending:true});}this.setData({party:p,coverImage:coverImage(p.coverPreset),startText:beijing(p.startAt),endText:beijing(p.plannedEndAt),firstEndText:p.firstEndedAt?beijing(p.firstEndedAt):'',statusText:p.status==='ENDED'?'已结束':p.reopened?'补充中':'活动中'});await this.prepareShare(g);}catch(e){if(this._visible&&g===this._generation){if(e instanceof ApiError&&e.code==='AUTH_REQUIRED')this.setData({loggedIn:false});this.setData({error:message(e)});}}finally{if(g===this._generation)this.setData({loading:false});}},
 async prepareShare(g:number){const p=this.data.party;if(!p?.canShare||this._attempt)return;try{const s=await partyRequest<{token:string}>(`/parties/${p.id}/share`);if(!this._visible||g!==this._generation||this._attempt)return;this._shareToken=s.token;this.setData({canShare:true,shareError:''});wx.showShareMenu({menus:['shareAppMessage']});}catch(e){if(this._visible&&g===this._generation)this.setData({shareError:'邀请暂不可用，请刷新后重试',canShare:false});}},
 onShareAppMessage(){const p=this.data.party;return p&&this.data.canShare&&this._shareToken?{title:`${p.theme} · ${p.location} · ${this.data.startText}`,path:`/subpackages/party/detail?token=${encodeURIComponent(this._shareToken)}`,imageUrl:this.data.coverImage}:{title:'我们的餐桌',path:'/pages/mine/index',imageUrl:'/assets/party-share.png'};},
 async join(){if(this.data.busy||this._attempt||!this.data.party?.canJoin)return;if(!await confirm('确认报名这次聚会？一个微信账号计1位成员。'))return;await this.perform({path:`/party-invitations/${encodeURIComponent(this.data.token)}/join`,method:'POST',body:{},key:key()});},
 async change(e:WechatMiniprogram.TouchEvent){if(this.data.busy||this._attempt||!this.data.party)return;const p=this.data.party;const action=e.currentTarget.dataset.action as string;const prompts:Record<string,string>={END:'结束后停止报名，成员与采购只读；需要补充时可重开。确认结束？',REOPEN:'重开后恢复有效邀请报名，原成员可继续补充。确认重开？',EXIT:'退出后撤销编辑权，真实垫付仍保留。确认退出？',DISABLE_INVITATION:'停用后旧卡片不能新增报名，已报名成员仍可查看。确认停用？',REGENERATE_INVITATION:'重新生成后旧卡片不能新增报名，需要分享新的邀请。确认重新生成？'};if(!prompts[action]||!await confirm(prompts[action]))return;await this.perform({path:`/parties/${p.id}`,method:'PUT',body:{version:p.version,action},key:key()});},
 coverError(){this.setData({coverImage:coverImage('DEFAULT')});},
 edit(){if(!this.data.busy&&!this._attempt&&this.data.party?.canEdit)wx.navigateTo({url:`/subpackages/party/edit?id=${this.data.party.id}`});},
 async removeMember(e:WechatMiniprogram.TouchEvent){if(this.data.busy||this._attempt)return;const p=this.data.party,m=p?.members.find(x=>x.userId===Number(e.currentTarget.dataset.id));if(!p?.canEdit||!m?.canRemove)return;if(!await confirm(`确认移除${m.name}？真实垫付及历史记录保留，分摊人数随之减少；旧邀请会失效，请重新分享邀请。`))return;await this.perform({path:`/parties/${p.id}/members/${m.userId}`,method:'PUT',body:{version:p.version},key:key()});},
 pendingKey(id:number,userId:number){return `partyDetailPending:${id}:${userId}`;},
 async retry(){if(!this.data.busy&&this._attempt){if(!wx.getStorageSync('sessionToken')){await this.signIn();if(!this.data.loggedIn)return;}await this.perform(this._attempt);}},
 async perform(a:Attempt){const p=this.data.party;if(!p)return;const user=this._attempt?this._attemptUser:p.userId;this._attempt=a;this._attemptUser=user;wx.setStorageSync(this.pendingKey(p.id,user),{userId:user,attempt:a});this._shareToken='';this.setData({busy:true,error:'',canShare:false});wx.hideShareMenu();let completed=false;try{const me=await request<Me>('/users/me');if(me.user.id!==user){this.setData({retryPending:true,error:'登录账号已变化，请重新进入聚会，原账号操作仍保留。'});return;}const result=await partyRequest<Party>(a.path,a.method,a.body,{'Idempotency-Key':a.key});this._attempt=null;wx.removeStorageSync(this.pendingKey(p.id,user));this.setData({retryPending:false,id:result.id,token:''});completed=true;}catch(e){const pending=uncertain(e);if(!pending){this._attempt=null;wx.removeStorageSync(this.pendingKey(p.id,user));}this.setData({error:message(e),retryPending:pending});if(!pending&&e instanceof ApiError&&e.code==='VERSION_CONFLICT'){const text=message(e);await this.load();this.setData({error:text+'。已加载最新状态，请重新确认操作。'});}}finally{this.setData({busy:false});if(completed&&this._visible)await this.load();}},
 purchases(){if(this.data.party?.membership)wx.navigateTo({url:`/subpackages/party/purchases?id=${this.data.party.id}`});},
 records(){wx.navigateTo({url:'/subpackages/party/index'});},mine(){wx.switchTab({url:'/pages/mine/index'});}
});
