import {ApiError,login,message,request,Me} from '../../services/api';
import {partyRequest,Party,Attempt,uncertain,time,partyCovers,coverImage,coverLabel} from '../../services/party';
import {key,confirm} from '../../services/menu';
interface Draft {theme:string;location:string;startDate:string;startTime:string;endDate:string;endTime:string;coverPreset?:string}
interface Pending {userId:number;partyId:number;attempt:Attempt;draft:Draft;original:Party}
function parts(value:string){const b=new Date(Date.parse(value)+8*3600000).toISOString();return{date:b.slice(0,10),time:b.slice(11,16)};}
function draft(p:Party):Draft{const a=parts(p.startAt),b=parts(p.plannedEndAt);return{theme:p.theme,location:p.location,startDate:a.date,startTime:a.time,endDate:b.date,endTime:b.time,coverPreset:p.coverPreset||'DEFAULT'};}
Page({data:{id:0,loggedIn:false,loading:false,busy:false,error:'',retryPending:false,conflicted:false,ready:false,startLocked:false,latest:null as Party|null,theme:'',location:'',startDate:'',startTime:'',endDate:'',endTime:'',coverPreset:'DEFAULT',coverImage:coverImage('DEFAULT'),covers:partyCovers},_visible:false,_generation:0,_original:null as Party|null,_user:0,_attempt:null as Attempt|null,
 onLoad(o:Record<string,string>){this.setData({id:/^[1-9]\d{0,16}$/.test(o.id||'')?Number(o.id):0});},async onShow(){this._visible=true;this.setData({loggedIn:!!wx.getStorageSync('sessionToken')});if(this.data.loggedIn)await this.load();},onHide(){this._visible=false;this._generation++;this.setData({loading:false});},onUnload(){this.onHide();},
 async signIn(){if(this.data.busy)return;try{await login();this.setData({loggedIn:true});await this.load();}catch(e){this.setData({error:message(e)});}},
 pendingKey(userId:number){return `partyEditPending:${this.data.id}:${userId}`;},
 async load(){const g=++this._generation;this.setData({loading:true,error:'',ready:false});try{const p=await partyRequest<Party>(`/parties/${this.data.id}`);if(!this._visible||g!==this._generation)return;if(this._user!==p.userId){this._attempt=null;this._original=null;this.setData({retryPending:false,conflicted:false,theme:'',location:'',startDate:'',startTime:'',endDate:'',endTime:'',coverPreset:'DEFAULT',coverImage:coverImage('DEFAULT')});}this._user=p.userId;this.setData({latest:p,ready:p.canEdit,startLocked:Date.parse(p.startAt)<=Date.parse(p.serverTime)});const pending=wx.getStorageSync<Pending>(this.pendingKey(p.userId));if(pending?.userId===p.userId&&pending.partyId===p.id){this._attempt=pending.attempt;this._original=pending.original;this.setData({...pending.draft,coverPreset:pending.draft.coverPreset||pending.original.coverPreset||'DEFAULT',coverImage:coverImage(pending.draft.coverPreset||pending.original.coverPreset),retryPending:true});}else if(!this._original){this._original=p;this.setData({...draft(p),coverImage:coverImage(p.coverPreset)});}else if(this._original.version!==p.version)this.setData({conflicted:true,error:'聚会已更新，输入保留。请核对最新信息后重新确认。'});if(!p.canEdit&&!this._attempt)this.setData({error:'仅创建者可修改活动中的聚会；已结束请先重开。'});}catch(e){if(this._visible&&g===this._generation){if(e instanceof ApiError&&e.code==='AUTH_REQUIRED')this.setData({loggedIn:false});this.setData({error:message(e)});}}finally{if(g===this._generation)this.setData({loading:false});}},
 input(e:WechatMiniprogram.CustomEvent<{value:string}>){if(this.data.busy||this._attempt)return;const field=e.currentTarget.dataset.field as string;if(['theme','location','startDate','startTime','endDate','endTime'].includes(field)&&!(this.data.startLocked&&field.startsWith('start')))this.setData({[field]:e.detail.value});},
 cover(e:WechatMiniprogram.TouchEvent){if(this.data.busy||this._attempt)return;const code=e.currentTarget.dataset.code as string;if(partyCovers.some(c=>c.code===code))this.setData({coverPreset:code,coverImage:coverImage(code)});},
 coverError(){this.setData({coverImage:coverImage('DEFAULT')});},
 async latest(){if(this.data.busy||this._attempt||!this.data.latest?.canEdit)return;const p=this.data.latest;if(!await confirm(`最新信息：${p.theme}，${p.location}；封面 ${coverLabel(p.coverPreset)}；时间 ${parts(p.startAt).date} ${parts(p.startAt).time} 至 ${parts(p.plannedEndAt).date} ${parts(p.plannedEndAt).time}。确认以此为基础修改？当前主题、地点和封面草稿会保留，时间恢复为最新值。`))return;this._original=p;const f=draft(p);this.setData({startDate:f.startDate,startTime:f.startTime,endDate:f.endDate,endTime:f.endTime,conflicted:false,error:''});},
 async submit(){if(this.data.busy)return;if(this._attempt){await this.send();return;}const p=this._original;if(!p||!this.data.ready||this.data.conflicted)return;try{const d=this.data,a=parts(p.startAt),b=parts(p.plannedEndAt);const startAt=d.startDate===a.date&&d.startTime===a.time?p.startAt:time(d.startDate,d.startTime),plannedEndAt=d.endDate===b.date&&d.endTime===b.time?p.plannedEndAt:time(d.endDate,d.endTime);const body={version:p.version,theme:d.theme.trim(),location:d.location.trim(),startAt,plannedEndAt,longDurationConfirmed:false,coverPreset:d.coverPreset};if(!body.theme||!body.location)throw new Error('请填写主题和地点');if(Date.parse(plannedEndAt)<=Date.parse(startAt))throw new Error('结束必须晚于开始');if((startAt!==p.startAt||plannedEndAt!==p.plannedEndAt)&&Date.parse(plannedEndAt)-Date.parse(startAt)>7*86400000){if(!await confirm('调整后聚会持续超过7天，确认使用当前起止时间？'))return;body.longDurationConfirmed=true;}this._attempt={path:`/parties/${d.id}/info`,method:'PUT',body,key:key()};wx.setStorageSync(this.pendingKey(this._user),{userId:this._user,partyId:d.id,attempt:this._attempt,original:p,draft:{theme:d.theme,location:d.location,startDate:d.startDate,startTime:d.startTime,endDate:d.endDate,endTime:d.endTime,coverPreset:d.coverPreset}} as Pending);await this.send();}catch(e){this.setData({error:message(e)});}},
 async send(){if(this.data.busy||!this._attempt)return;this.setData({busy:true,error:''});try{const me=await request<Me>('/users/me');if(me.user.id!==this._user){this.setData({retryPending:true,error:'登录账号已变化，原账号操作已保留，请重新进入页面。'});return;}const a=this._attempt;await partyRequest<Party>(a.path,a.method,a.body,{'Idempotency-Key':a.key});this._attempt=null;wx.removeStorageSync(this.pendingKey(this._user));this.setData({retryPending:false});if(this._visible)wx.redirectTo({url:`/subpackages/party/detail?id=${this.data.id}`});}catch(e){const pending=uncertain(e);if(!pending){this._attempt=null;wx.removeStorageSync(this.pendingKey(this._user));}this.setData({retryPending:pending,error:message(e)});if(!pending&&e instanceof ApiError&&['VERSION_CONFLICT','PARTY_ALREADY_STARTED','PARTY_ENDED'].includes(e.code)){const error=message(e);await this.load();this.setData({conflicted:true,error:error+'。输入保留，请核对最新信息后重新确认。'});}}finally{this.setData({busy:false});}},
 detail(){wx.redirectTo({url:`/subpackages/party/detail?id=${this.data.id}`});}
});
