import {ApiError,login,message} from '../../services/api';
import {partyRequest,Purchase,Purchases,Attempt,uncertain,Member} from '../../services/party';
import {key,confirm} from '../../services/menu';
interface Draft {name:string;quantity:string;amount:string;zeroNote:string;reason:string;assigneeIndex:number;payerIndex:number;selected:Purchase|null;editing:boolean}
interface Pending {partyId:number;userId:number;attempt:Attempt;draft:Draft}
const empty=():Draft=>({name:'',quantity:'',amount:'',zeroNote:'',reason:'',assigneeIndex:0,payerIndex:0,selected:null,editing:false});
Page({data:{id:0,loggedIn:false,loading:false,busy:false,error:'',retryPending:false,conflicted:false,showAdvances:false,listing:null as Purchases|null,page:1,assignees:[] as Member[],payers:[] as Member[],...empty()},_visible:false,_generation:0,_attempt:null as Attempt|null,_attemptUser:0,_loadedUser:0,
 onLoad(o:Record<string,string>){this.setData({id:/^[1-9]\d{0,16}$/.test(o.id||'')?Number(o.id):0});},async onShow(){this._visible=true;this.setData({loggedIn:!!wx.getStorageSync('sessionToken')});if(this.data.loggedIn)await this.load();},onHide(){this._visible=false;this._generation++;this.setData({loading:false});},onUnload(){this.onHide();},
 async signIn(){if(this.data.busy)return;this.setData({busy:true,error:''});try{await login();this.setData({loggedIn:true});await this.load();}catch(e){this.setData({error:message(e)});}finally{this.setData({busy:false});}},
 async load(){const g=++this._generation;this.setData({loading:true,error:'',listing:null});try{const listing=await partyRequest<Purchases>(`/parties/${this.data.id}/items?page=${this.data.page}`);if(!this._visible||g!==this._generation)return;if(this._loadedUser && this._loadedUser!==listing.userId){this._attempt=null;this.setData({...empty(),retryPending:false,conflicted:false});}this._loadedUser=listing.userId;this.setData({listing,assignees:[{userId:0,name:'待认领',status:'JOINED'},...(listing.creator?listing.candidates:listing.candidates.filter(m=>m.userId===listing.userId))],payers:listing.candidates});
 const pending=wx.getStorageSync<Pending>(this.pendingKey(listing.userId));if(pending?.partyId===this.data.id){if(pending.userId===listing.userId){this._attempt=pending.attempt;this._attemptUser=pending.userId;this.setData({...pending.draft,retryPending:true});this.payerOptions(pending.draft.selected);}else{this._attempt=null;this.setData({retryPending:false,...empty()});wx.removeStorageSync(this.pendingKey(this._attemptUser));this.setData({error:'登录账号已更换，上次操作需使用原账号核对。'});}}
 }catch(e){if(this._visible&&g===this._generation){if(e instanceof ApiError&&e.code==='AUTH_REQUIRED')this.setData({loggedIn:false});this.setData({error:message(e)});}}finally{if(g===this._generation)this.setData({loading:false});}},
 async page(e:WechatMiniprogram.TouchEvent){if(this.data.busy||this._attempt||this.data.editing)return;const page=Number(e.currentTarget.dataset.page);if(page>=1&&page<=25){this.setData({page});await this.load();}},
 toggleAdvances(){this.setData({showAdvances:!this.data.showAdvances});},
 scrollEditor(){wx.nextTick(()=>{if(this._visible)wx.pageScrollTo({selector:'#purchase-editor',duration:180,fail:()=>{}});});},
 payerOptions(item:Purchase|null){const listing=this.data.listing;if(!listing)return;const payers=[...listing.candidates];if(item?.payerId&&!payers.some(p=>p.userId===item.payerId))payers.push({userId:item.payerId,name:(item.payerName||'原垫付人')+'（已退出）',status:'EXITED'});this.setData({payers});},
 add(){if(this.data.busy||this._attempt||!this.data.listing?.canAdd)return;this.setData({...empty(),editing:true,conflicted:false,error:''});this.payerOptions(null);const i=this.data.payers.findIndex(p=>p.userId===this.data.listing?.userId);this.setData({payerIndex:Math.max(0,i)});this.scrollEditor();},
 edit(e:WechatMiniprogram.TouchEvent){if(this.data.busy||this._attempt)return;const item=this.data.listing?.items.find(i=>i.id===Number(e.currentTarget.dataset.id));if(item)this.open(item);},
 open(item:Purchase){this.payerOptions(item);this.setData({...empty(),editing:true,selected:item,name:item.name,quantity:item.quantity||'',amount:item.amount||'',zeroNote:item.zeroNote||'',assigneeIndex:Math.max(0,this.data.assignees.findIndex(m=>m.userId===item.assigneeId)),payerIndex:Math.max(0,this.data.payers.findIndex(m=>m.userId===(item.payerId||this.data.listing?.userId))),conflicted:false,error:''});this.scrollEditor();},
 cancel(){if(this.data.busy||this._attempt)return;this.setData({...empty(),conflicted:false});},
 input(e:WechatMiniprogram.Input){if(this.data.busy||this._attempt)return;const field=e.currentTarget.dataset.field as string;if(['name','quantity','amount','zeroNote','reason'].includes(field))this.setData({[field]:e.detail.value});},
 pick(e:WechatMiniprogram.PickerChange){if(this.data.busy||this._attempt)return;const field=e.currentTarget.dataset.field as string;if(['assigneeIndex','payerIndex'].includes(field))this.setData({[field]:Number(e.detail.value)});},
 async latest(){if(this.data.busy||this._attempt||!this.data.selected||!await confirm('加载最新项目会替换当前未保存输入，确认继续？'))return;try{const item=await partyRequest<Purchase>(`/parties/${this.data.id}/items/${this.data.selected.id}`);if(this._visible)this.open(item);}catch(e){this.setData({error:message(e)});}},
 async saveInfo(){if(this.blocked())return;const d=this.data;const body=d.selected?{version:d.selected.version,action:'EDIT',name:d.name,quantity:d.quantity}:{name:d.name,quantity:d.quantity,assigneeId:d.assignees[d.assigneeIndex]?.userId||null};await this.perform({path:`/parties/${d.id}/items${d.selected?'/'+d.selected.id:''}`,method:d.selected?'PUT':'POST',body,key:key()});},
 async assign(){if(this.blocked()||!this.data.selected||!this.data.listing?.creator)return;await this.mutate('ASSIGN',{assigneeId:this.data.assignees[this.data.assigneeIndex]?.userId||null});},
 async purchase(){if(this.blocked()||!this.data.selected?.canPurchase)return;if(!/^(?:0|[1-9]\d{0,4})(?:\.\d{1,2})?$/.test(this.data.amount)){this.setData({error:'金额须为0—99999.99元，最多两位小数'});return;}if(Number(this.data.amount)===0&&!this.data.zeroNote.trim()){this.setData({error:'0元请填写赠送或自有等说明'});return;}if(this.data.selected.status==='PURCHASED'&&!this.data.reason.trim()){this.setData({error:'修改已购金额或垫付人请填写原因'});return;}if(!await confirm(this.data.selected.status==='PURCHASED'?'确认修正购买记录？费用将随之更新。':'确认已经购买？将按填写金额记录实际垫付。'))return;await this.mutate('PURCHASE',{amount:this.data.amount,payerId:this.data.payers[this.data.payerIndex]?.userId,zeroNote:this.data.zeroNote,reason:this.data.reason});},
 async remove(e:WechatMiniprogram.TouchEvent){if(this.blocked()||!this.data.selected?.canEdit)return;const action=e.currentTarget.dataset.action as string;if(!['REMOVE','REVERT'].includes(action))return;const bought=this.data.selected.status==='PURCHASED';if(bought&&!this.data.reason.trim()){this.setData({error:'请填写移除或撤回的原因'});return;}if(!await confirm(action==='REVERT'?'确认撤回为待购买？本次垫付将移出汇总，原记录保留。':bought?'确认移除已购物品？费用将扣除，原记录和原因保留。':'确认移除这个采购项目？'))return;await this.mutate(action,{reason:this.data.reason,confirmed:true});},
 async quick(e:WechatMiniprogram.TouchEvent){if(this.blocked()||this.data.editing)return;const item=this.data.listing?.items.find(i=>i.id===Number(e.currentTarget.dataset.id));const action=e.currentTarget.dataset.action as string;if(!item||!['CLAIM','RELEASE'].includes(action))return;if(!await confirm(action==='CLAIM'?'确认由你采购这件物品？':'确认解除认领，交回待认领清单？'))return;await this.perform({path:`/parties/${this.data.id}/items/${item.id}`,method:'PUT',body:{version:item.version,action},key:key()});},
 blocked(){return this.data.busy||!!this._attempt||this.data.conflicted||!this.data.listing?.canAdd;},
 async mutate(action:string,fields:object){const item=this.data.selected;if(!item)return;await this.perform({path:`/parties/${this.data.id}/items/${item.id}`,method:'PUT',body:{version:item.version,action,...fields},key:key()});},
 pendingKey(userId:number){return `partyPurchasePending:${this.data.id}:${userId}`;},
 draft():Draft{const d=this.data;return{name:d.name,quantity:d.quantity,amount:d.amount,zeroNote:d.zeroNote,reason:d.reason,assigneeIndex:d.assigneeIndex,payerIndex:d.payerIndex,selected:d.selected,editing:d.editing};},
 async retry(){if(this.data.busy||!this._attempt)return;if(!wx.getStorageSync('sessionToken')){await this.signIn();if(!this.data.loggedIn||!this._attempt)return;}if(this.data.listing?.userId!==this._attemptUser){this.setData({error:'请先加载聚会，核对登录账号后再重试。'});return;}await this.perform(this._attempt);},
 async perform(a:Attempt){const userId=this._attempt?this._attemptUser:this.data.listing?.userId;if(!userId)return;this._attempt=a;this._attemptUser=userId;wx.setStorageSync(this.pendingKey(userId),{partyId:this.data.id,userId,attempt:a,draft:this.draft()} as Pending);this.setData({busy:true,error:''});try{await partyRequest<Purchase>(a.path,a.method,a.body,{'Idempotency-Key':a.key});this._attempt=null;wx.removeStorageSync(this.pendingKey(this._attemptUser));this.setData({retryPending:false,conflicted:false,...empty()});if(this._visible)await this.load();}catch(e){const pending=uncertain(e);if(!pending){this._attempt=null;wx.removeStorageSync(this.pendingKey(this._attemptUser));}this.setData({retryPending:pending,error:message(e)});if(!pending&&e instanceof ApiError&&['VERSION_CONFLICT','PARTY_ENDED','PARTY_MEMBER_ONLY'].includes(e.code)){const error=message(e);await this.load();this.setData({conflicted:!!this.data.selected,error:error+'。已刷新清单，当前输入保留；加载最新项目后重新确认。'});}}finally{this.setData({busy:false});}},
 detail(){wx.navigateTo({url:`/subpackages/party/detail?id=${this.data.id}`});}
});
