const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
function compile(file){return ts.transpileModule(fs.readFileSync(path.join(__dirname,'../miniprogram',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;}
class ApiError extends Error{constructor(code,msg){super(msg);this.code=code;}}
function fixture(version=2){return{order:{id:10,restaurantName:'我的厨房',date:'2026-10-04',meal:'DINNER',version,items:[{id:20,dishId:1,dishName:'牛腩',quantity:1,selections:[]}]},candidates:[{id:1,name:'牛腩',version:0,dimensions:[]},{id:2,name:'青菜',version:0,dimensions:[]}]};}
function page(request,confirmation=async()=>true){let p;const redirects=[];vm.runInNewContext(compile('pages/orders/confirm.ts'),{exports:{},require:n=>n.endsWith('/api')?{ApiError,dailyGuard:async()=>true,message:e=>e.message}:n.endsWith('/menu')?{key:()=>'stable_completion_key',confirm:confirmation}:{orderingRequest:request,mealNames:{DINNER:'晚餐'}},Page:d=>p=d,wx:{redirectTo:r=>redirects.push(r)}});p.setData=patch=>Object.assign(p.data,patch);p._visible=true;p.setData({id:10,ready:true});return{p,redirects};}
test('确认前发现点单数量变化，保留实际菜品调整并展示最新点单',async()=>{let current=fixture(),writes=0;const{p}=page(async(u,m='GET')=>{if(m==='POST')writes++;return current;});await p.reload(true);p.quantity({currentTarget:{dataset:{id:p.data.rows[0].localId,delta:1}}});current=fixture(3);current.order.items[0].quantity=4;await p.save();assert.equal(writes,0);assert.equal(p.data.rows[0].input.quantity,2);assert.match(p.data.notice,/4份/);assert.equal(p.data.version,3);});
test('原菜品规格被改，连续保存也不能默默采用新的快照',async()=>{let current=fixture(),writes=0;const{p}=page(async(u,m='GET')=>{if(m==='POST')writes++;return current;});await p.reload(true);current=fixture(3);current.order.items[0].selections=[{optionName:'重辣'}];await p.save();await p.save();assert.equal(writes,0);assert.match(p.data.error,/牛腩/);});
test('完成请求超时冻结草稿，重试同键同内容且不创建第二张完成记录',async()=>{const calls=[];let fail=true;const{p,redirects}=page(async(u,m='GET',body,headers)=>{if(m==='GET')return fixture();calls.push({u,body,headers});if(fail){fail=false;throw new ApiError('NETWORK_ERROR','超时');}return{orderId:10,version:3};});await p.reload(true);await p.save();assert.equal(p.data.retryPending,true);p.remove({currentTarget:{dataset:{id:p.data.rows[0].localId}}});assert.equal(p.data.rows.length,1);await p.retry();assert.equal(calls.length,2);assert.deepEqual(calls[0],calls[1]);assert.equal(redirects.length,1);});
test('空实际清单拒绝完成，并在取消重新载入时保留本地调整',async()=>{let allow=false,writes=0;const{p}=page(async(u,m='GET')=>{if(m==='POST')writes++;return fixture();},async()=>allow);await p.reload(true);p.remove({currentTarget:{dataset:{id:p.data.rows[0].localId}}});await p.save();assert.equal(writes,0);await p.reset();assert.equal(p.data.rows.length,0);allow=true;await p.reset();assert.equal(p.data.rows.length,1);});
test('补选菜菜单变动时保留调整并阻止使用旧规格版本',async()=>{let current=fixture(),writes=0;const{p}=page(async(u,m='GET')=>{if(m==='POST')writes++;return current;});await p.reload(true);p.choose(1);p.add();current=fixture();current.candidates[1].version=1;await p.save();assert.equal(writes,0);assert.equal(p.data.rows.length,2);assert.match(p.data.error,/青菜/);assert.equal(p.data.candidates[1].version,1);});
test('餐单列表隐藏期间的响应不覆盖重进页面且可以继续加载',async()=>{let p,resolve;let requests=0;const old=new Promise(r=>resolve=r);vm.runInNewContext(compile('pages/orders/index.ts'),{exports:{},require:n=>n.endsWith('/api')?{dailyGuard:async()=>true,message:e=>e.message}:n.endsWith('/orders')?{stateNames:{IN_PROGRESS:'进行中'}}:{orderingRequest:async()=>++requests===1?old:{orders:[],page:1,hasMore:false},mealNames:{DINNER:'晚餐'}},Page:d=>p=d,wx:{getStorageSync:()=>false},setInterval:()=>1,clearInterval(){}});p.setData=v=>Object.assign(p.data,v);p.getTabBar=()=>null;p._visible=true;const first=p.load();p.onHide();assert.equal(p.data.loading,false);await p.onShow();resolve({orders:[{id:999}],page:1,hasMore:false});await first;assert.equal(requests,2);assert.equal(p.data.orders.length,0);assert.equal(p.data.loading,false);});

test('已结束或失去权限的确认页不能继续发起完成或没做操作',async()=>{let writes=0;const{p}=page(async(u,m='GET')=>{if(m==='POST')writes++;throw new ApiError('MEAL_ENDED','餐单已结束');});await p.reload(true);assert.equal(p.data.available,false);await p.save();await p.notCooked();assert.equal(writes,0);assert.match(p.data.error,/已结束/);});
