const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
function compile(file){return ts.transpileModule(fs.readFileSync(path.join(__dirname,'../miniprogram',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;}
const helpers={};vm.runInNewContext(compile('services/home.ts'),{exports:helpers});
class ApiError extends Error{constructor(code,message){super(message);this.code=code;}}
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};}
function summary(count=2){return{today:'2026-10-04',greeting:'晚上好',period:'week',scope:'family',rangeStart:'2026-09-28',rangeEnd:'2026-10-04',restaurants:[{id:1,name:'我的厨房'},{id:2,name:'她的厨房'}],cookCount:count,trend:[{label:'周一',date:'2026-09-28',count, future:false}],popular:[],recommendation:null};}
function page(request,allowed=true){let p;const calls=[],actions=[],tab=[];vm.runInNewContext(compile('pages/home/index.ts'),{exports:{},require:n=>n.endsWith('/home')?helpers:{request:async(...args)=>{calls.push(args);return request(...args);},dailyGuard:async()=>allowed?{}:null,ApiError,message:e=>e.message},Page:d=>p=d,wx:{navigateTo:r=>actions.push(r),switchTab:r=>actions.push(r),setStorageSync:(k,v)=>actions.push({key:k,value:v}),stopPullDownRefresh(){}},Date});p.setData=v=>Object.assign(p.data,v);p.getTabBar=()=>({setData:v=>tab.push(v)});p._visible=true;p.setData({ready:true});return{p,calls,actions,tab};}
test('首页切换周期忽略迟到旧响应，不串统计范围',async()=>{const first=deferred(),second=deferred();let calls=0;const{p}=page(()=>++calls===1?first.promise:second.promise);const old=p.load();p.period({currentTarget:{dataset:{key:'month'}}});second.resolve(summary(7));await second.promise;await new Promise(r=>setImmediate(r));first.resolve(summary(2));await old;assert.equal(p.data.summary.cookCount,7);assert.equal(p.data.period,'month');});
test('首页隐藏期间的失败与结果不覆盖重进页面',async()=>{const d=deferred(),{p}=page(()=>d.promise);const loading=p.load();p.onHide();d.resolve(summary(99));await loading;assert.equal(p.data.summary,null);assert.equal(p.data.loading,false);});
test('首页网络失败保留错误，不伪造零统计',async()=>{const{p}=page(async()=>{throw new ApiError('NETWORK_ERROR','连接失败');});p.setData({summary:summary(20)});await p.load();assert.equal(p.data.summary,null);assert.equal(p.data.popular.length,0);assert.equal(p.data.error,'连接失败');});
test('日常资格失效隐藏统计与导航，受限用户不请求首页',async()=>{const first=page(async()=>{throw new ApiError('ACCESS_REQUIRED','请验证密令');});await first.p.load();assert.equal(first.p.data.ready,false);assert.equal(first.tab.at(-1).daily,false);assert.equal(first.actions.at(-1).url,'/pages/access/index');const second=page(async()=>summary(),false);await second.p.onShow();assert.equal(second.calls.length,0);assert.equal(second.p.data.ready,false);});
test('趋势零值和未到日期分别呈现，月份轴标签不过密',()=>{const points=Array.from({length:31},(_,i)=>({date:`2026-10-${i+1}`,label:String(i+1),count:i===0?4:i<4?0:null,future:i>=4}));const result=helpers.chart(points,'month');assert.equal(result[0].height,140);assert.equal(result[1].height,0);assert.equal(result[4].height,0);assert.equal(result[4].text,'未到');assert.equal(result.filter(p=>p.tick).length,8);assert.equal(helpers.score(4),'4.0 分');assert.equal(helpers.score(null),'暂无评分');});
test('全家同名菜带餐厅标记，评价数不冒充人数',async()=>{const data=summary();data.popular=[{dishId:1,dishName:'牛腩',restaurantName:'我的厨房',orderCount:3,average:4,reviewCount:2}];const{p}=page(async()=>data);await p.load();assert.equal(p.data.popular[0].displayName,'牛腩 · 我的厨房');assert.equal(p.data.popular[0].scoreText,'4.0 分');assert.equal(p.data.popular[0].reviewCount,2);p.scope({detail:{value:1}});assert.equal(p.data.scope,'restaurant:1');});
test('时令推荐只传递所属餐厅与菜品，不自动点菜',async()=>{const data=summary();data.recommendation={restaurantId:2,dishId:30,dishName:'南瓜汤',restaurantName:'她的厨房',average:null,reviewCount:0};const{p,actions,calls}=page(async()=>data);await p.load();p.recommend();assert.equal(actions[0].key,'orderingTarget');assert.deepEqual(JSON.parse(JSON.stringify(actions[0].value)),{restaurantId:2,dishId:30});assert.equal(actions[1].url,'/pages/ordering/index');assert.ok(calls.every(([,method])=>!method||method==='GET'));});
