const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
class ApiError extends Error{constructor(code,message){super(message);this.code=code;}}
function setup(){const exports={},storage=new Map(),calls=[];let callback,key=0,fail=false;const code=ts.transpileModule(fs.readFileSync(__dirname+'/../miniprogram/services/notifications.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
 vm.runInNewContext(code,{exports,require:n=>n.endsWith('/api')?{ApiError}:n.endsWith('/menu')?{key:()=>`consent_key_${++key}`}:{orderingRequest:async(path,method,body,headers)=>{calls.push({type:'server',path,body,headers});if(fail)throw new ApiError('NETWORK_ERROR','连接失败');return {}; }},wx:{getStorageSync:k=>storage.get(k),setStorageSync:(k,v)=>storage.set(k,v),removeStorageSync:k=>storage.delete(k),requestSubscribeMessage:options=>{calls.push({type:'sdk'});callback=options;}}});
 const subscription={userId:1,event:'REVIEW_INVITED',templateId:'review-template',enabled:true,response:'UNKNOWN',available:0};
 return{exports,subscription,calls,storage,success:value=>callback.success({'review-template':value}),failure:()=>callback.fail(),setFail:value=>fail=value};
}
test('用户点击时同步调用微信SDK，服务器登记在SDK回调之后',async()=>{const x=setup(),promise=x.exports.authorize(x.subscription);assert.equal(x.calls.length,1);assert.equal(x.calls[0].type,'sdk');x.success('accept');assert.equal(await promise,'已订阅一次提醒');assert.equal(x.calls[1].body.response,'ACCEPT');assert.equal(x.storage.size,0);});
test('登记超时保留原幂等键，重试不再次弹窗或重复累计',async()=>{const x=setup();x.setFail(true);const a=x.exports.authorize(x.subscription);x.success('accept');await assert.rejects(a);assert.equal(x.storage.size,1);x.setFail(false);await x.exports.authorize(x.subscription);const requests=x.calls.filter(c=>c.type==='server');assert.equal(x.calls.filter(c=>c.type==='sdk').length,1);assert.equal(requests[0].headers['Idempotency-Key'],requests[1].headers['Idempotency-Key']);assert.equal(x.storage.size,0);});
test('双击只弹出一次授权',async()=>{const x=setup(),a=x.exports.authorize(x.subscription);await assert.rejects(x.exports.authorize(x.subscription));x.success('accept');await a;assert.equal(x.calls.filter(c=>c.type==='sdk').length,1);});
test('拒绝和过滤不记作同意',async()=>{for(const [value,expected] of [['reject','REJECT'],['ban','BAN'],['filter','UNKNOWN'],['acceptWithAudio','ACCEPT']]){const x=setup(),p=x.exports.authorize(x.subscription);x.success(value);await p;assert.equal(x.calls[1].body.response,expected);}});
test('SDK失败不登记授权，再次点击仍可弹出',async()=>{const x=setup(),a=x.exports.authorize(x.subscription);x.failure();await assert.rejects(a);assert.equal(x.storage.size,0);const b=x.exports.authorize(x.subscription);x.success('accept');await b;assert.equal(x.calls.filter(c=>c.type==='server').length,1);});
test('用户切换后不会重放其他人的待登记授权',async()=>{const x=setup();x.setFail(true);const a=x.exports.authorize(x.subscription);x.success('accept');await assert.rejects(a);x.setFail(false);const b=x.exports.authorize({...x.subscription,userId:2});x.success('accept');await b;assert.equal(x.calls[2].type,'sdk');assert.equal(x.calls[3].body.userId,2);assert.equal(x.storage.size,1);});
test('未启用模板不弹窗',async()=>{const x=setup();await assert.rejects(x.exports.authorize({...x.subscription,enabled:false}));assert.equal(x.calls.length,0);});
test('API已受理文案不宣称微信已送达或已读',()=>{const x=setup();assert.match(x.exports.notificationNames.SENT,/已受理/);assert.doesNotMatch(x.exports.notificationNames.SENT,/已送达|已读/);});

test('待登记超过幂等保留期时不重放旧回调，重新请求微信授权',async()=>{const x=setup();x.storage.set('subscriptionPending:1:REVIEW_INVITED',{body:{userId:1,event:'REVIEW_INVITED',templateId:'review-template',response:'ACCEPT'},key:'expired-key',createdAt:Date.now()-24*3600000});const p=x.exports.authorize(x.subscription);assert.equal(x.calls[0].type,'sdk');x.success('reject');await p;assert.equal(x.calls[1].body.response,'REJECT');});
