const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
function compile(relative){return ts.transpileModule(fs.readFileSync(path.join(__dirname,'../miniprogram',relative),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;}
const orderExports={};vm.runInNewContext(compile('services/orders.ts'),{exports:orderExports});
class ApiError extends Error{constructor(code,message){super(message);this.code=code;}}
function preview(version=1,quantity=1){return {order:{id:10,version,restaurantName:'我的厨房',date:'2026-10-03',meal:'DINNER',status:'DRAFT',dinerCount:2,remark:null,canMeta:false,items:[],pendingItems:[{id:20,dishName:'牛腩',quantity,contributorName:'朋友',selections:[]}],participants:[]},invalidItems:[],canSubmit:true,menuFingerprint:'menu-'+version};}
function page(request){let p;const redirects=[];vm.runInNewContext(compile('pages/orders/submit.ts'),{exports:{},require:n=>n.endsWith('/api')?{ApiError,dailyGuard:async()=>true,message:e=>e.message}:n.endsWith('/menu')?{key:()=>'stable_operation_key'}:n.endsWith('/orders')?orderExports:{orderingRequest:request,mealNames:{DINNER:'晚餐'}},Page:d=>p=d,wx:{redirectTo:r=>redirects.push(r)},setInterval:()=>1,clearInterval(){}});p.setData=patch=>Object.assign(p.data,patch);p._visible=true;p.setData({id:10,ready:true});return{p,redirects};}
test('提交前发现他人增菜，展示差异并要求再次核对，保留备注输入',async()=>{let current=preview();let writes=0;const{p}=page(async(u,m='GET')=>{if(m==='POST')writes++;return current;});await p.refresh();p.setData({remark:'不要香菜'});current=preview(2,3);await p.submit();assert.equal(writes,0);assert.equal(p.data.changed,true);assert.match(p.data.notice,/3份/);assert.equal(p.data.remark,'不要香菜');p.acknowledge();assert.equal(p.data.version,2);assert.equal(p.data.remark,'不要香菜');});
test('提交超时同键重试，不修改原提交内容或重复累计份数',async()=>{const calls=[];let fail=true;const{p,redirects}=page(async(u,m='GET',body,headers)=>{calls.push({u,m,body,headers});if(m==='GET')return u.includes('preview')?preview():{};if(fail){fail=false;throw new ApiError('NETWORK_ERROR','超时');}return{orderId:10,version:2};});await p.refresh();await p.submit();assert.equal(p.data.retryPending,true);p.remark({detail:{value:'不应覆盖'}});assert.equal(p.data.remark,'');await p.submit();const writes=calls.filter(c=>c.m==='POST');assert.equal(writes.length,2);assert.deepEqual(writes[0].body,writes[1].body);assert.equal(writes[0].headers['Idempotency-Key'],writes[1].headers['Idempotency-Key']);assert.equal(redirects.length,1);});
test('强制提交复核覆盖轮询中的旧响应',async()=>{let resolve;const old=new Promise(r=>resolve=r);let call=0;const{p}=page(async()=>++call===1?old:preview(3,4));p.apply(preview());const polling=p.refresh();await p.refresh(true);resolve(preview());await polling;assert.equal(p._latest.order.version,3);assert.equal(p.data.changed,true);});
test('失效菜品阻止提交并保持其余有效选择',async()=>{const data=preview();data.invalidItems=[{itemId:20,reason:'菜品已下架'}];data.canSubmit=false;const{p}=page(async()=>data);await p.refresh();assert.equal(p.data.canSubmit,false);assert.equal(p.data.rows.length,1);assert.equal(p.data.rows[0].invalid,'菜品已下架');});
test('完成提交后没有追加清单，不自动重复提交',async()=>{let writes=0;const{p}=page(async(u,m='GET')=>{if(m==='POST')writes++;const d=preview(2);d.order.status='IN_PROGRESS';d.order.pendingItems=[];d.canSubmit=false;return d;});await p.refresh();await p.submit();assert.equal(writes,0);assert.equal(p.data.canSubmit,false);});
