const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
function compile(file){return ts.transpileModule(fs.readFileSync(path.join(__dirname,'../miniprogram',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;}
class ApiError extends Error{constructor(code,message){super(message);this.code=code;}}
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};}
function party(extra={}){return{id:7,userId:1,canEdit:false,serverTime:'2026-10-05T03:00:00Z',theme:'朋友一起吃饭',location:'家里',startAt:'2026-10-06T10:00:00Z',plannedEndAt:'2026-10-06T14:00:00Z',status:'ACTIVE',reopened:false,firstEndedAt:null,lastEndedAt:null,version:2,memberCount:2,creator:false,membership:'JOINED',canJoin:false,canShare:true,dailyAllowed:false,members:[{userId:1,name:'Kai',status:'JOINED'}],...extra};}
function harness(file,request,options={}){let p;const storage=new Map(options.storage||[['sessionToken','local-test']]),actions=[],calls=[],sharing=[];let serial=0;const partyExports={};vm.runInNewContext(compile('services/party.ts'),{exports:partyExports,require:n=>n.endsWith('/api')?{ApiError,request(){}}:{PARTY_API_BASE:'local-party'}});partyExports.partyRequest=async(...a)=>{calls.push(a);return request(...a);};const api={ApiError,message:e=>e.message,login:async()=>({user:{id:1},dailyAllowed:false}),request:async()=>({user:{id:1},dailyAllowed:options.daily??false}),dailyGuard:async()=>({user:{id:options.user||1},dailyAllowed:true})};const menu={key:()=>`attempt_${String(++serial).padStart(16,'0')}`,confirm:async()=>options.confirm!==false};const wx={nextTick:f=>f(),pageScrollTo(){},getStorageSync:k=>storage.get(k),setStorageSync:(k,v)=>storage.set(k,v),removeStorageSync:k=>storage.delete(k),navigateTo:v=>actions.push(v),redirectTo:v=>actions.push(v),switchTab:v=>actions.push(v),hideShareMenu:()=>sharing.push(false),showShareMenu:()=>sharing.push(true)};const requireFn=n=>n.endsWith('/party')?partyExports:n.endsWith('/menu')?menu:n.endsWith('/reviews')?{beijing:v=>v}:api;
if(file==='list'){const e={};vm.runInNewContext(compile('services/party-list.ts'),{exports:e,require:requireFn,wx});p=e.partyList(false);}else vm.runInNewContext(compile('subpackages/party/'+file+'.ts'),{exports:{},require:requireFn,wx,Date,Page:d=>p=d});p.setData=v=>Object.assign(p.data,v);p.getTabBar=()=>({setData(){}});p._visible=true;return{p,storage,actions,calls,sharing,partyExports};}
test('未报名邀请只渲染摘要、不准备分享，登录不要求日常密令',async()=>{const h=harness('detail',async()=>party({members:[],memberCount:null,membership:null,canJoin:true,canShare:false}));h.p.onLoad({token:'invited'});await h.p.onShow();assert.equal(h.p.data.party.members.length,0);assert.equal(h.calls.length,1);assert.match(h.calls[0][0],/party-invitations/);assert.equal(h.p.data.canShare,false);});
test('隐藏后的旧邀请响应不能恢复成员内容或分享入口',async()=>{const d=deferred(),h=harness('detail',()=>d.promise);h.p.onLoad({id:'7'});const loaded=h.p.onShow();h.p.onHide();d.resolve(party());await loaded;assert.equal(h.p.data.party,null);assert.equal(h.p.data.canShare,false);assert.equal(h.calls.length,1);});
test('过期邀请错误不展示上次聚会及旧分享卡片',async()=>{const h=harness('detail',async()=>{throw new ApiError('PARTY_UNAVAILABLE','邀请已停用');});h.p.onLoad({token:'disabled'});h.p.setData({party:party(),canShare:true});await h.p.onShow();assert.equal(h.p.data.party,null);assert.equal(h.p.data.canShare,false);assert.equal(h.p.onShareAppMessage().path,'/pages/mine/index');});
test('报名结果不明保留同一操作键、重试后按成员身份读取',async()=>{let failed=false;const h=harness('detail',async(p,m)=>{if(m==='POST'){if(!failed){failed=true;throw new ApiError('NETWORK_ERROR','连接失败');}return party();}if(p.endsWith('/share'))return{token:'new-shared'};return party();});h.p.onLoad({token:'invite'});h.p.setData({party:party({canJoin:true,membership:null}),loggedIn:true});await h.p.join();assert.equal(h.p.data.retryPending,true);const key=h.p._attempt.key;await h.p.retry();const writes=h.calls.filter(([,m])=>m==='POST');assert.equal(writes.length,2);assert.equal(writes[0][3]['Idempotency-Key'],key);assert.equal(writes[1][3]['Idempotency-Key'],key);assert.equal(h.p.data.token,'');assert.ok(h.calls.some(([p])=>p==='/parties/7'));});
test('结束操作需确认，版本冲突加载新状态并要求重新确认',async()=>{const denied=harness('detail',async()=>party(),{confirm:false});denied.p.setData({party:party({creator:true})});await denied.p.change({currentTarget:{dataset:{action:'END'}}});assert.equal(denied.calls.length,0);const h=harness('detail',async(p,m)=>{if(m==='PUT')throw new ApiError('VERSION_CONFLICT','内容已更新');return party({version:3,canShare:false});});h.p.setData({id:7,party:party({creator:true})});await h.p.change({currentTarget:{dataset:{action:'END'}}});assert.equal(h.p._attempt,null);assert.equal(h.p.data.party.version,3);assert.match(h.p.data.error,/重新确认/);});
test('创建网络失败跨页面恢复原输入和操作键，不重复创建',async()=>{const first=harness('create',async()=>{throw new ApiError('NETWORK_ERROR','断网');});first.p.onLoad();await first.p.onShow();first.p.setData({theme:'一起聚会',location:'家里',startDate:'2026-10-06',endDate:'2026-10-06'});await first.p.submit();assert.equal(first.p.data.retryPending,true);const saved=first.storage.get('partyCreatePending');const next=harness('create',async()=>party(),{storage:[...first.storage]});next.p.onLoad();await next.p.onShow();assert.equal(next.p.data.theme,'一起聚会');assert.equal(next.p._attempt.key,saved.attempt.key);next.p.input({currentTarget:{dataset:{field:'theme'}},detail:{value:'换了主题'}});assert.equal(next.p.data.theme,'一起聚会');await next.p.submit();assert.equal(next.calls[0][3]['Idempotency-Key'],saved.attempt.key);assert.equal(next.storage.has('partyCreatePending'),false);assert.equal(next.actions.at(-1).url,'/subpackages/party/detail?id=7');});
test('超7天创建二次确认，拒绝不发请求；日期统一为北京时间',async()=>{const h=harness('create',async()=>party(),{confirm:false});h.p.onLoad();await h.p.onShow();h.p.setData({theme:'长聚会',location:'这里',startDate:'2026-10-06',endDate:'2026-10-15'});await h.p.submit();assert.equal(h.calls.length,0);assert.equal(h.partyExports.time('2026-10-06','18:00'),'2026-10-06T18:00:00+08:00');});
test('受限用户可看本人聚会，列表快速切换忽略旧响应',async()=>{const old=deferred(),next=deferred();let count=0;const h=harness('list',()=>++count===1?old.promise:next.promise);h.p.setData({loggedIn:true});const loaded=h.p.load();await new Promise(r=>setImmediate(r));h.p.tab({currentTarget:{dataset:{state:'ENDED'}}});await new Promise(r=>setImmediate(r));next.resolve({parties:[party({theme:'历史聚会',status:'ENDED'})],page:1,hasMore:false});await new Promise(r=>setImmediate(r));old.resolve({parties:[party()],page:1,hasMore:false});await loaded;assert.equal(h.p.data.parties[0].theme,'历史聚会');assert.equal(h.p.data.daily,false);h.p.create();assert.equal(h.actions.length,0);});

test('聚会分享使用固定封面，避免自动截图泄露成员名单',async()=>{const h=harness('detail',async(p)=>p.endsWith('/share')?{token:'safe-token'}:party());h.p.onLoad({id:'7'});await h.p.onShow();const card=h.p.onShareAppMessage();assert.equal(card.imageUrl,'/assets/party-share.png');assert.equal(card.path,'/subpackages/party/detail?token=safe-token');assert.ok(!card.title.includes('Kai'));});

function purchase(extra={}){return{id:13,name:'牛肉',quantity:'2斤',creatorId:1,assigneeId:null,assigneeName:null,status:'TODO',payerId:null,payerName:null,amount:null,zeroNote:null,version:0,canEdit:true,canClaim:true,canRelease:false,canPurchase:false,...extra};}
function purchases(extra={}){return{items:[purchase()],page:1,hasMore:false,summary:{total:'0.00',perPerson:'0.00',memberCount:2,itemCount:1,purchasedCount:0,advances:[{userId:1,name:'Kai',status:'JOINED',amount:'0.00'}]},canAdd:true,creator:true,userId:1,candidates:[{userId:1,name:'Kai',status:'JOINED'},{userId:2,name:'朋友',status:'JOINED'}],...extra};}
test('采购读取失败不伪造零元账单，未登录提供原页面登录',async()=>{const h=harness('purchases',async()=>{throw new ApiError('PARTY_UNAVAILABLE','需先报名');});h.p.onLoad({id:'7'});await h.p.onShow();assert.equal(h.p.data.listing,null);assert.match(h.p.data.error,/报名/);});
test('普通成员添加仅可选自己或待认领，已退出付款人仍可回看',async()=>{const h=harness('purchases',async()=>purchases({creator:false,summary:{total:'100.00',perPerson:'50.00',memberCount:2,itemCount:1,purchasedCount:1,advances:[{userId:3,name:'退出朋友',status:'EXITED',amount:'100.00'}]}}));h.p.onLoad({id:'7'});await h.p.onShow();assert.deepEqual(Array.from(h.p.data.assignees,m=>m.userId),[0,1]);assert.equal(h.p.data.listing.summary.total,'100.00');h.p.open(purchase({status:'PURCHASED',payerId:3,payerName:'退出朋友',amount:'100.00'}));assert.equal(h.p.data.payers.at(-1).userId,3);assert.match(h.p.data.payers.at(-1).name,/已退出/);});
test('采购失败跨页面保留输入和原操作编号，成功后刷新最新费用',async()=>{let failed=true;const h=harness('purchases',async(p,m)=>{if(m==='POST'){if(failed){failed=false;throw new ApiError('NETWORK_ERROR','断网');}return purchase();}return purchases();});h.p.onLoad({id:'7'});await h.p.onShow();h.p.add();h.p.setData({name:'蔬菜',quantity:'一袋'});await h.p.saveInfo();assert.equal(h.p.data.retryPending,true);const saved=h.storage.get('partyPurchasePending:7:1');h.p.input({currentTarget:{dataset:{field:'name'}},detail:{value:'别的'}});assert.equal(h.p.data.name,'蔬菜');const next=harness('purchases',async(p,m)=>m==='POST'?purchase():purchases(),{storage:[...h.storage]});next.p.onLoad({id:'7'});await next.p.onShow();assert.equal(next.p.data.quantity,'一袋');await next.p.retry();const write=next.calls.find(([,m])=>m==='POST');assert.equal(write[3]['Idempotency-Key'],saved.attempt.key);assert.equal(next.storage.has('partyPurchasePending:7:1'),false);assert.equal(next.p.data.editing,false);});
test('认领竞争刷新当前负责人，版本冲突保留草稿并要求重新确认',async()=>{const current=purchase({version:1,assigneeId:2,assigneeName:'朋友',canEdit:false,canClaim:false});const h=harness('purchases',async(p,m)=>{if(m==='PUT')throw new ApiError('VERSION_CONFLICT','已被更新');return purchases({items:[current]});});h.p.onLoad({id:'7'});h.p.setData({listing:purchases(),selected:purchase(),editing:true,name:'我输入的名称'});await h.p.saveInfo();assert.equal(h.p.data.name,'我输入的名称');assert.equal(h.p.data.selected.version,0);assert.equal(h.p.data.conflicted,true);assert.equal(h.p.data.listing.items[0].assigneeName,'朋友');await h.p.saveInfo();assert.equal(h.calls.filter(([,m])=>m==='PUT').length,1);});
test('三位小数、零元无备注不发购买请求，已购删除须说明且二次确认',async()=>{const h=harness('purchases',async()=>purchase());h.p.setData({id:7,listing:purchases(),selected:purchase({assigneeId:1,canPurchase:true}),amount:'1.999'});await h.p.purchase();assert.equal(h.calls.length,0);h.p.setData({amount:'0'});await h.p.purchase();assert.equal(h.calls.length,0);h.p.setData({selected:purchase({status:'PURCHASED'}),reason:''});await h.p.remove({currentTarget:{dataset:{action:'REMOVE'}}});assert.equal(h.calls.length,0);const denied=harness('purchases',async()=>purchase(),{confirm:false});denied.p.setData({id:7,listing:purchases(),selected:purchase({status:'PURCHASED'}),reason:'重复'});await denied.p.remove({currentTarget:{dataset:{action:'REMOVE'}}});assert.equal(denied.calls.length,0);});
test('隐藏后的采购响应不能恢复费用，结束只读拦截陈旧表单',async()=>{const d=deferred(),h=harness('purchases',()=>d.promise);h.p.onLoad({id:'7'});const loading=h.p.onShow();h.p.onHide();d.resolve(purchases());await loading;assert.equal(h.p.data.listing,null);h.p.setData({listing:purchases({canAdd:false}),selected:purchase({canPurchase:true}),amount:'10'});await h.p.purchase();assert.equal(h.calls.length,1);});

test('切换账号不重放另一账号的未决采购，原账号仍可核对',async()=>{let user=1;const h=harness('purchases',async(p,m)=>{if(m==='POST')throw new ApiError('NETWORK_ERROR','断网');return purchases({userId:user});});h.p.onLoad({id:'7'});await h.p.onShow();h.p.add();h.p.setData({name:'苹果'});await h.p.saveInfo();const key=h.p._attempt.key;user=2;await h.p.load();assert.equal(h.p._attempt,null);assert.equal(h.p.data.retryPending,false);assert.equal(h.p.data.name,'');assert.ok(h.storage.has('partyPurchasePending:7:1'));await h.p.retry();assert.equal(h.calls.filter(([,m])=>m==='POST').length,1);user=1;await h.p.load();assert.equal(h.p._attempt.key,key);assert.equal(h.p.data.name,'苹果');});

test('修改聚会保留原时刻精度并以北京时间展示，过去的计划时间可原样保存',async()=>{const original=party({canEdit:true,creator:true,startAt:'2026-10-02T10:00:37Z',plannedEndAt:'2026-10-02T14:00:21Z'});const h=harness('edit',async()=>original);h.p.onLoad({id:'7'});await h.p.onShow();assert.equal(h.p.data.startLocked,true);assert.equal(h.p.data.startTime,'18:00');h.p.input({currentTarget:{dataset:{field:'startTime'}},detail:{value:'20:00'}});assert.equal(h.p.data.startTime,'18:00');h.p.setData({theme:'改主题'});await h.p.submit();const write=h.calls.find(([,m])=>m==='PUT');assert.equal(write[2].startAt,original.startAt);assert.equal(write[2].plannedEndAt,original.plannedEndAt);assert.equal(h.actions.at(-1).url,'/subpackages/party/detail?id=7');});
test('修改未知结果跨页面恢复同键和草稿，期间即使结束也可核对原请求',async()=>{const original=party({canEdit:true,creator:true});const h=harness('edit',async(p,m)=>{if(m==='PUT')throw new ApiError('NETWORK_ERROR','断网');return original;});h.p.onLoad({id:'7'});await h.p.onShow();h.p.setData({theme:'原草稿'});await h.p.submit();const pending=h.storage.get('partyEditPending:7:1');assert.ok(pending);const next=harness('edit',async(p,m)=>m==='PUT'?original:party({status:'ENDED',canEdit:false}),{storage:[...h.storage]});next.p.onLoad({id:'7'});await next.p.onShow();assert.equal(next.p.data.theme,'原草稿');assert.equal(next.p.data.ready,false);await next.p.submit();assert.equal(next.calls.find(([,m])=>m==='PUT')[3]['Idempotency-Key'],pending.attempt.key);assert.equal(next.storage.has('partyEditPending:7:1'),false);});
test('修改版本冲突保留草稿，显式核对最新基线后才可再次保存',async()=>{let version=2;const h=harness('edit',async(p,m)=>{if(m==='PUT'){version=3;throw new ApiError('VERSION_CONFLICT','已更新');}return party({version,canEdit:true,creator:true,theme:'最新主题'});});h.p.onLoad({id:'7'});await h.p.onShow();h.p.setData({theme:'我的草稿'});await h.p.submit();assert.equal(h.p.data.theme,'我的草稿');assert.equal(h.p.data.conflicted,true);await h.p.submit();assert.equal(h.calls.filter(([,m])=>m==='PUT').length,1);await h.p.latest();assert.equal(h.p._original.version,3);assert.equal(h.p.data.theme,'我的草稿');assert.equal(h.p.data.conflicted,false);});
test('编辑页隐藏或切换账号不恢复旧内容、不重放原账号未决保存',async()=>{const d=deferred(),hidden=harness('edit',()=>d.promise);hidden.p.onLoad({id:'7'});const loading=hidden.p.onShow();hidden.p.onHide();d.resolve(party({canEdit:true}));await loading;assert.equal(hidden.p._original,null);let user=1;const h=harness('edit',async(p,m)=>{if(m==='PUT')throw new ApiError('NETWORK_ERROR','断网');return party({userId:user,canEdit:true,theme:'新账号'});});h.p.onLoad({id:'7'});await h.p.onShow();await h.p.submit();assert.ok(h.storage.has('partyEditPending:7:1'));user=2;await h.p.load();assert.equal(h.p._attempt,null);assert.equal(h.p.data.retryPending,false);assert.equal(h.p.data.theme,'新账号');});
test('移除成员须确认，发送前撤销分享，未知结果跨页面核对同键',async()=>{const original=party({creator:true,canEdit:true,members:[{userId:2,name:'朋友',status:'JOINED',canRemove:true}]});const declined=harness('detail',async()=>original,{confirm:false});declined.p.setData({party:original});await declined.p.removeMember({currentTarget:{dataset:{id:2}}});assert.equal(declined.calls.length,0);const h=harness('detail',async(p,m)=>{if(m==='PUT')throw new ApiError('NETWORK_ERROR','断网');if(p.endsWith('/share'))return{token:'old'};return original;});h.p.onLoad({id:'7'});await h.p.onShow();assert.equal(h.p.data.canShare,true);await h.p.removeMember({currentTarget:{dataset:{id:2}}});assert.equal(h.p.data.canShare,false);assert.equal(h.p._shareToken,'');const pending=h.storage.get('partyDetailPending:7:1');const next=harness('detail',async(p,m)=>m==='PUT'?party({memberCount:1}):p.endsWith('/share')?{token:'rotated'}:party(),{storage:[...h.storage]});next.p.onLoad({id:'7'});await next.p.onShow();assert.equal(next.p.data.canShare,false);await next.p.retry();assert.equal(next.calls.find(([,m])=>m==='PUT')[3]['Idempotency-Key'],pending.attempt.key);assert.match(next.p.onShareAppMessage().path,/rotated/);assert.equal(next.storage.has('partyDetailPending:7:1'),false);});
test('待采购阻止移除并清除未决状态，成功移除才展示新邀请',async()=>{const original=party({creator:true,canEdit:true,members:[{userId:2,name:'朋友',status:'JOINED',canRemove:true}]});const h=harness('detail',async(p,m)=>{if(m==='PUT')throw new ApiError('PENDING_PURCHASES','请先解除待采购任务');return original;});h.p.onLoad({id:'7'});h.p.setData({party:original});await h.p.removeMember({currentTarget:{dataset:{id:2}}});assert.match(h.p.data.error,/待采购/);assert.equal(h.p._attempt,null);assert.equal(h.storage.has('partyDetailPending:7:1'),false);});
test('结束或普通成员不能打开修改页、发起移除',async()=>{const h=harness('detail',async()=>party());h.p.setData({party:party({canEdit:false,members:[{userId:2,canRemove:false}]})});h.p.edit();await h.p.removeMember({currentTarget:{dataset:{id:2}}});assert.equal(h.actions.length,0);assert.equal(h.calls.length,0);});
test('移除中的旧分享响应不能恢复旧邀请',async()=>{const sharing=deferred(),mutation=deferred();const original=party({creator:true,canEdit:true,members:[{userId:2,name:'朋友',status:'JOINED',canRemove:true}]});let updated=false;const h=harness('detail',async(p,m)=>{if(m==='PUT'){const result=await mutation.promise;updated=true;return result;}return p.endsWith('/share')?sharing.promise:updated?party({canShare:false}):original;});h.p.onLoad({id:'7'});const loading=h.p.onShow();await new Promise(r=>setImmediate(r));const removing=h.p.removeMember({currentTarget:{dataset:{id:2}}});await new Promise(r=>setImmediate(r));sharing.resolve({token:'old-invite'});await loading;assert.equal(h.p.data.canShare,false);assert.equal(h.p._shareToken,'');mutation.resolve(party({canShare:false}));await removing;assert.equal(h.p._shareToken,'');});
test('未登录成员登录回到聚会后可以准备分享',async()=>{const h=harness('detail',async p=>p.endsWith('/share')?{token:'after-login'}:party(),{storage:[]});h.p.onLoad({id:'7'});await h.p.onShow();assert.equal(h.calls.length,0);await h.p.signIn();assert.equal(h.p.data.loggedIn,true);assert.equal(h.p.data.canShare,true);assert.match(h.p.onShareAppMessage().path,/after-login/);});

test('预设封面创建保存选择、断网恢复同一封面，未决状态禁止重新选择',async()=>{const h=harness('create',async()=>{throw new ApiError('NETWORK_ERROR','断网');});h.p.onLoad();await h.p.onShow();h.p.setData({theme:'一起火锅',location:'这里',startDate:'2026-10-10',endDate:'2026-10-10'});h.p.cover({currentTarget:{dataset:{code:'HOT_POT'}}});await h.p.submit();const pending=h.storage.get('partyCreatePending');assert.equal(pending.attempt.body.coverPreset,'HOT_POT');h.p.cover({currentTarget:{dataset:{code:'TEA'}}});assert.equal(h.p.data.coverPreset,'HOT_POT');const next=harness('create',async()=>party({coverPreset:'HOT_POT'}),{storage:[...h.storage]});next.p.onLoad();await next.p.onShow();assert.match(next.p.data.coverImage,/hot-pot-v1.png$/);await next.p.submit();assert.equal(next.calls[0][2].coverPreset,'HOT_POT');assert.equal(next.calls[0][3]['Idempotency-Key'],pending.attempt.key);});
test('编辑读取原封面、显式恢复默认，结果不明跨页保留封面草稿',async()=>{const original=party({canEdit:true,coverPreset:'TABLE'});const h=harness('edit',async(p,m)=>m==='PUT'?Promise.reject(new ApiError('NETWORK_ERROR','断网')):original);h.p.onLoad({id:'7'});await h.p.onShow();assert.equal(h.p.data.coverPreset,'TABLE');h.p.cover({currentTarget:{dataset:{code:'DEFAULT'}}});await h.p.submit();const next=harness('edit',async()=>original,{storage:[...h.storage]});next.p.onLoad({id:'7'});await next.p.onShow();assert.equal(next.p.data.coverPreset,'DEFAULT');assert.equal(next.p.data.coverImage,'/assets/party-share.png');assert.equal(next.p._attempt.body.coverPreset,'DEFAULT');});
test('封面冲突保留本次选择，核对最新信息不静默改写封面草稿',async()=>{let changed=false;const h=harness('edit',async(p,m)=>{if(m==='PUT'){changed=true;throw new ApiError('VERSION_CONFLICT','更新');}return party({canEdit:true,version:changed?3:2,coverPreset:changed?'HOT_POT':'TABLE'});});h.p.onLoad({id:'7'});await h.p.onShow();h.p.cover({currentTarget:{dataset:{code:'TEA'}}});await h.p.submit();assert.equal(h.p.data.conflicted,true);assert.equal(h.p.data.coverPreset,'TEA');await h.p.latest();assert.equal(h.p._original.coverPreset,'HOT_POT');assert.equal(h.p.data.coverPreset,'TEA');});
test('详情及微信卡片用所选封面，加载失败安全回退，不截图成员',async()=>{const h=harness('detail',async p=>p.endsWith('/share')?{token:'safe'}:party({coverPreset:'TEA'}));h.p.onLoad({id:'7'});await h.p.onShow();assert.equal(h.p.data.coverImage,'/assets/party/tea-v1.png');assert.equal(h.p.onShareAppMessage().imageUrl,h.p.data.coverImage);h.p.coverError();assert.equal(h.p.onShareAppMessage().imageUrl,'/assets/party-share.png');assert.equal(h.partyExports.coverImage('../../unsafe.png'),'/assets/party-share.png');});
test('聚会列表展示历史封面，单项图片失败不改存储的选择或其他卡片',async()=>{const h=harness('list',async()=>({parties:[party({coverPreset:'TABLE'}),party({id:8,coverPreset:'HOT_POT'})],page:1,hasMore:false}));await h.p.onShow();assert.equal(h.p.data.parties[0].coverImage,'/assets/party/table-v1.png');h.p.coverError({currentTarget:{dataset:{id:7}}});assert.equal(h.p.data.parties[0].coverImage,'/assets/party-share.png');assert.equal(h.p.data.parties[0].coverPreset,'TABLE');assert.equal(h.p.data.parties[1].coverImage,'/assets/party/hot-pot-v1.png');});
