const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const source=ts.transpileModule(fs.readFileSync(path.join(__dirname,'../miniprogram/pages/ordering/index.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
class ApiError extends Error{constructor(code,message){super(message);this.code=code;}}
const dish={id:30,categoryId:7,name:'南瓜汤',introduction:'暖暖的',version:1,dimensions:[],average:4,reviewCount:2,hot:true};
function page({ended=false,offSeason=false}={}){let p;const requests=[],target={restaurantId:2,dishId:30};const slot={date:'2026-10-31',meal:'DINNER'};const menus={categories:[{id:7,name:'季节限定'}],dishes:offSeason?[]:[dish]};vm.runInNewContext(source,{exports:{},require:n=>n.endsWith('/api')?{dailyGuard:async()=>({}),ApiError,message:e=>e.message,request:async u=>{requests.push(['GET',u]);return u==='/restaurants'?[{id:1,name:'我的厨房'},{id:2,name:'她的厨房'}]:structuredClone(menus);}}:n.endsWith('/cart')?{mealNames:{DINNER:'晚餐'},orderingRequest:async(u,m='GET')=>{requests.push([m,u]);if(u==='/meal-slots')return{slots:[slot,{date:'2026-11-01',meal:'DINNER'}],defaultSlot:slot};if(ended)throw new ApiError('CART_NOT_DRAFT','该餐次已结束');return{orderId:null,version:0,status:'DRAFT',serverTime:'2026-10-31T10:00:00Z',cutoff:'2026-10-31T13:00:00Z',items:[],submittedItems:[],dishCount:0,quantity:0,contributorCount:0};}}:n.endsWith('/orders')?{selections:rows=>rows}:{key:()=> 'request_key',confirm:async()=>true},Page:d=>p=d,wx:{getStorageSync:()=>target,removeStorageSync(){},showToast(){}},setInterval:()=>1,clearInterval(){},Date,structuredClone});p.setData=v=>Object.assign(p.data,v);p.getTabBar=()=>({setData(){}});return{p,requests};}
test('跨店时令入口打开目标菜详情，保留清单且不自动写入',async()=>{const{p,requests}=page();await p.onShow();assert.equal(p.data.restaurantIndex,1);assert.equal(p.data.date,'2026-10-31');assert.equal(p.data.dish.id,30);assert.equal(p.data.dish.scoreText,'4.0 分');assert.equal(p.data.closed,false);assert.ok(requests.some(([,u])=>u.includes('/restaurants/2/menu')));assert.ok(requests.every(([method])=>method==='GET'));});
test('时令目标餐次已结束仍可看菜单，但不能直接加菜',async()=>{const{p,requests}=page({ended:true});await p.onShow();assert.equal(p.data.dish.id,30);assert.equal(p.data.closed,true);assert.match(p.data.syncError,/切换日期或餐次/);await p.saveDish();assert.ok(requests.every(([method])=>method==='GET'));});
test('所选日期不供应时令菜，保留日期并提示重新选择',async()=>{const{p,requests}=page({offSeason:true});p.setData({date:'2026-11-01',meal:'DINNER'});await p.onShow();assert.equal(p.data.dish,null);assert.equal(p.data.date,'2026-11-01');assert.match(p.data.syncError,/所选用餐日期不可选/);assert.ok(requests.some(([,u])=>u.endsWith('date=2026-11-01')));assert.ok(requests.every(([method])=>method==='GET'));});

test('未核对的跨店操作不会被推荐入口覆盖或丢失',async()=>{const{p,requests}=page();const original={orderId:10,items:[{id:1,quantity:2}]};p.setData({retryPending:true,cart:original,restaurantIndex:0});p._pending={path:'/meal-orders/10/items',body:{dishId:20},key:'same_key'};await p.onShow();assert.equal(p.data.cart,original);assert.equal(p.data.restaurantIndex,0);assert.equal(p._targetDish,null);assert.equal(p._pending.path,'/meal-orders/10/items');assert.match(p.data.syncError,/先核对上一次/);assert.equal(requests.length,0);});
