const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
function compile(file){return ts.transpileModule(fs.readFileSync(path.join(__dirname,'../miniprogram',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;}
const reviewExports={};vm.runInNewContext(compile('services/reviews.ts'),{exports:reviewExports});
class ApiError extends Error{constructor(code,msg){super(msg);this.code=code;}}
function sheet(mine=null){return{orderId:10,restaurantName:'我的厨房',date:'2026-10-04',meal:'DINNER',serverTime:'2026-10-04T08:00:00Z',deadline:'2026-10-11T08:00:00Z',canSubmit:true,reviewedCount:mine?1:0,foods:[{dishId:20,dishName:'牛腩',quantity:2,specifications:['微辣','重辣'],average:null,reviewCount:0,mine}]};}
function page(request,options={}){let p,session=options.session!==false;const requests=[],shares=[];vm.runInNewContext(compile('subpackages/reviews/sheet.ts'),{exports:{},require:n=>n.endsWith('/api')?{ApiError,login:async()=>{session=true;return{dailyAllowed:false};},message:e=>e.message}:n.endsWith('/menu')?{key:()=>'stable_review_operation',confirm:async()=>true}:n.endsWith('/reviews')?reviewExports:{orderingRequest:async(...args)=>{requests.push(args);return request(...args);},mealNames:{DINNER:'晚餐'}},Page:d=>p=d,wx:{getStorageSync:()=>session,hideShareMenu:()=>shares.push('hide'),showShareMenu:()=>shares.push('show'),showToast(){}},setTimeout:()=>1,clearTimeout(){},Date});p.setData=v=>Object.assign(p.data,v);p._visible=true;p.onLoad(options.token?{token:options.token}:{id:'10'});return{p,requests,shares};}
function routine(data){return async(u,m='GET')=>u.endsWith('review-shares')?{token:'t'.repeat(43),expiresAt:data.deadline}:m==='GET'?data:{};}
test('首次评价没有默认评分，选星前不能提交',async()=>{const{p,requests}=page(routine(sheet()));await p.load();p.edit({currentTarget:{dataset:{id:20}}});assert.equal(p.data.rating,0);await p.submit();assert.equal(requests.filter(([u,m])=>m==='POST'&&!u.endsWith('review-shares')).length,0);p.rate({currentTarget:{dataset:{star:3}}});await p.submit();const write=requests.find(([u])=>u.endsWith('/reviews'));assert.equal(write[2].rating,3);assert.equal(write[2].dishId,20);});
test('分享入口登录后回到原邀请，无日常密令请求',async()=>{const token='g'.repeat(43),{p,requests}=page(routine(sheet()),{session:false,token});await p.onShow();assert.equal(requests.length,0);await p.signIn();assert.equal(p.data.loggedIn,true);assert.equal(requests[0][0],'/review-invitations/'+token);assert.ok(!requests.some(([u])=>u.includes('access')||u.includes('meal-orders/10/review-sheet')));});
test('分享卡片只使用受限令牌路径和固定封面，不含个人输入',async()=>{const{p}=page(routine(sheet()));await p.load();p.setData({comment:'私密评论',rating:4});const card=p.onShareAppMessage();assert.equal(card.path,'/subpackages/reviews/sheet?token='+'t'.repeat(43));assert.equal(card.imageUrl,'/assets/review-share.png');assert.ok(!JSON.stringify(card).includes('私密评论'));p._expiresLocal=Date.now()-1;assert.equal(p.onShareAppMessage().path,'/pages/mine/index');});
test('评价提交超时冻结输入并同键同内容重试',async()=>{let fail=true;const{p,requests}=page(async(u,m='GET')=>{if(u.endsWith('review-shares'))return{token:'t'.repeat(43)};if(m==='GET')return sheet();if(fail){fail=false;throw new ApiError('NETWORK_ERROR','超时');}return{};});await p.load();p.edit({currentTarget:{dataset:{id:20}}});p.rate({currentTarget:{dataset:{star:4}}});p.text({detail:{value:'好吃'}});await p.submit();assert.equal(p.data.retryPending,true);p.text({detail:{value:'不能覆盖'}});assert.equal(p.data.comment,'好吃');await p.retry();const writes=requests.filter(([u])=>u.endsWith('/reviews'));assert.equal(writes.length,2);assert.deepEqual(writes[0],writes[1]);});
test('过期页不开放新评分或分享，但保留已发表评价',async()=>{const data=sheet({id:30,rating:4,comment:'好吃',canModify:false});data.canSubmit=false;const{p,requests}=page(routine(data));await p.load();p.edit({currentTarget:{dataset:{id:20}}});assert.equal(p.data.editor,null);assert.equal(p.data.canShare,false);assert.equal(p.data.foods[0].mine.rating,4);assert.equal(requests.length,1);});
test('评价版本冲突保留输入，已消耗修改机会不会自动采用新版本',async()=>{let current=sheet({id:30,version:0,rating:4,comment:'原文',canModify:true});const{p}=page(async(u,m='GET')=>{if(u.endsWith('review-shares'))return{token:'t'.repeat(43)};if(m==='GET')return current;current=sheet({id:30,version:1,rating:3,comment:'另一设备',canModify:false});throw new ApiError('VERSION_CONFLICT','版本已更新');});await p.load();p.edit({currentTarget:{dataset:{id:20}}});p.text({detail:{value:'当前输入'}});await p.submit();assert.equal(p.data.comment,'当前输入');assert.equal(p._editorVersion,0);await p.checkLatest();assert.equal(p._editorVersion,0);assert.match(p.data.error,/已锁定/);});
test('分享准备失败不会阻止正常评价或生成空令牌卡片',async()=>{const{p}=page(async(u)=>{if(u.endsWith('review-shares'))throw new ApiError('NETWORK_ERROR','超时');return sheet();});await p.load();assert.equal(p.data.sheet.foods.length,1);assert.equal(p.data.canShare,false);assert.match(p.data.shareError,/暂不可用/);assert.equal(p.onShareAppMessage().path,'/pages/mine/index');});

test('本人评价列表会话过期重新显示登录，保留所选入口',async()=>{let p,authorized=false;vm.runInNewContext(compile('subpackages/reviews/index.ts'),{exports:{},require:n=>n.endsWith('/api')?{ApiError,login:async()=>{authorized=true;},message:e=>e.message}:n.endsWith('/reviews')?reviewExports:{orderingRequest:async u=>{assert.equal(u,'/my/reviews?page=1');if(!authorized)throw new ApiError('AUTH_REQUIRED','请重新登录');return{reviews:[],page:1,hasMore:false};},mealNames:{DINNER:'晚餐'}},Page:d=>p=d,wx:{getStorageSync:()=>true},Date});p.setData=v=>Object.assign(p.data,v);p.onLoad({});p.setData({state:'mine',reviews:[{id:30}],loggedIn:true});await p.onShow();assert.equal(p.data.loggedIn,false);assert.equal(p.data.reviews.length,0);assert.equal(p.data.state,'mine');await p.signIn();assert.equal(p.data.loggedIn,true);assert.equal(p.data.error,'');});
