import {ApiError,dailyGuard,message} from '../../services/api';
import {orderingRequest,Mutation,mealNames} from '../../services/cart';
import {confirm,key} from '../../services/menu';
import {Confirmation,Candidate,ActualInput} from '../../services/orders';
interface Row { localId:number; name:string; specText:string; input:ActualInput; snapshot:string }
interface Attempt { path:string; body:object; key:string }
Page({
 data:{id:0,ready:false,available:false,loading:true,busy:false,error:'',notice:'',retryPending:false,title:'',date:'',rows:[] as Row[],candidates:[] as Candidate[],candidateIndex:0,choices:[] as {name:string;options:{id:number;name:string}[];index:number}[],version:0},
 _visible:false,_loaded:false,_sequence:0,_latest:null as Confirmation|null,_attempt:null as Attempt|null,
 onLoad(options:Record<string,string>){this.setData({id:Number(options.id)});},
 async onShow(){this._visible=true;if(!await dailyGuard()||!this._visible)return;this.setData({ready:true});if(!this._loaded)await this.reload(true);},
 onHide(){this._visible=false;},onUnload(){this._visible=false;},
 back(){wx.redirectTo({url:`/pages/orders/detail?id=${this.data.id}`});},
 async reset(){await this.reload(false);},
 async reload(initial=false){if(this.data.busy||this._attempt)return;if(!initial&&!await confirm('重新载入会清空当前调整，按最新点单重新核对。'))return;this.setData({loading:true,available:false,error:''});try{const latest=await orderingRequest<Confirmation>(`/chef/meal-orders/${this.data.id}/confirmation-preview`);if(!this._visible)return;this._latest=latest;this._loaded=true;this.setData({available:true,title:latest.order.restaurantName,date:latest.order.date+' · '+mealNames[latest.order.meal],version:latest.order.version,candidates:latest.candidates,rows:latest.order.items.map(i=>({localId:++this._sequence,name:i.dishName,specText:i.selections.map(s=>s.dimensionName+'：'+s.optionName).join(' · '),input:{sourceOrderItemId:i.id,quantity:i.quantity},snapshot:JSON.stringify([i.dishName,i.selections])})),notice:''});this.choose(0);}catch(e){this.setData({error:message(e)});}finally{this.setData({loading:false});}},
 choose(index:number){const dish=this.data.candidates[index];this.setData({candidateIndex:index,choices:dish?dish.dimensions.map(d=>({name:d.name,options:d.options,index:Math.max(0,d.options.findIndex(o=>o.isDefault))})):[]});},
 candidate(e:WechatMiniprogram.PickerChange){if(!this.data.busy&&!this._attempt)this.choose(Number(e.detail.value));},
 option(e:WechatMiniprogram.PickerChange){if(this.data.busy||this._attempt)return;const choices=this.data.choices.map((c,i)=>i===Number(e.currentTarget.dataset.index)?{...c,index:Number(e.detail.value)}:c);this.setData({choices});},
 add(){if(this.data.busy||this._attempt)return;const dish=this.data.candidates[this.data.candidateIndex];if(!dish)return;if(this.data.rows.length>=100){this.setData({error:'最多100行实际菜品'});return;}const options=this.data.choices.map(c=>c.options[c.index]);if(options.some(o=>!o)){this.setData({error:'该菜规格不完整，请先维护菜单'});return;}this.setData({rows:[...this.data.rows,{localId:++this._sequence,name:dish.name,specText:this.data.choices.map((c,i)=>c.name+'：'+options[i].name).join(' · '),input:{dishId:dish.id,dishVersion:dish.version,optionIds:options.map(o=>o.id),quantity:1},snapshot:''}]});},
 remove(e:WechatMiniprogram.TouchEvent){if(!this.data.busy&&!this._attempt)this.setData({rows:this.data.rows.filter(r=>r.localId!==Number(e.currentTarget.dataset.id))});},
 quantity(e:WechatMiniprogram.TouchEvent){if(this.data.busy||this._attempt)return;const id=Number(e.currentTarget.dataset.id),delta=Number(e.currentTarget.dataset.delta);this.setData({rows:this.data.rows.map(r=>r.localId===id?{...r,input:{...r.input,quantity:Math.max(1,Math.min(99,r.input.quantity+delta))}}:r)});},
 async save(){if(!this.data.available)return;if(this.data.busy||this._attempt)return;if(!this.data.rows.length){this.setData({error:'至少保留一道实际菜品；没有做饭请选择“这顿没做”'});return;}this.setData({busy:true,error:''});try{const latest=await orderingRequest<Confirmation>(`/chef/meal-orders/${this.data.id}/confirmation-preview`);this.setData({candidates:latest.candidates});this.choose(Math.min(this.data.candidateIndex,Math.max(0,latest.candidates.length-1)));const invalid=this.data.rows.filter(r=>r.input.sourceOrderItemId?!latest.order.items.some(i=>i.id===r.input.sourceOrderItemId&&JSON.stringify([i.dishName,i.selections])===r.snapshot):!latest.candidates.some(c=>c.id===r.input.dishId&&c.version===r.input.dishVersion));if(invalid.length){this.setData({error:invalid.map(r=>r.name).join('、')+' 的原菜品或菜单已改变，请移除后重选，或重新载入点单。'});return;}if(latest.order.version!==this.data.version){this._latest=latest;this.setData({notice:'最新原点单：'+latest.order.items.map(i=>i.dishName+' '+i.quantity+'份 '+i.selections.map(s=>s.optionName).join('/')).join('、')+'。已保留实际菜品调整，请核对后再次确认。',version:latest.order.version});return;}if(!await confirm('确认实际做过这些菜？完成后不能修改。尚未提交的追加不会计入。'))return;await this.perform({path:`/chef/meal-orders/${this.data.id}/complete`,body:{version:this.data.version,items:this.data.rows.map(r=>r.input)},key:key()});}catch(e){this.setData({error:message(e)});}finally{this.setData({busy:false});}},
 async notCooked(){if(!this.data.available)return;if(this.data.busy||this._attempt)return;const version=this.data.version;if(!await confirm('标记这顿没做？餐单将取消，不计入做饭次数。'))return;await this.perform({path:`/chef/meal-orders/${this.data.id}/not-cooked`,body:{version,reason:'这顿没做'},key:key()});},
 async retry(){if(this._attempt&&!this.data.busy&&await dailyGuard())await this.perform(this._attempt);},
 async perform(attempt:Attempt){this._attempt=attempt;this.setData({busy:true,error:''});try{if(this.data.retryPending)await orderingRequest(`/meal-orders/${this.data.id}`);await orderingRequest<Mutation>(attempt.path,'POST',attempt.body,{'Idempotency-Key':attempt.key});this._attempt=null;this.setData({retryPending:false});wx.redirectTo({url:`/pages/orders/detail?id=${this.data.id}`});}catch(e){const uncertain=e instanceof ApiError&&['NETWORK_ERROR','SERVICE_UNAVAILABLE','ACCESS_REQUIRED','AUTH_REQUIRED'].includes(e.code);if(!uncertain)this._attempt=null;this.setData({error:message(e),retryPending:uncertain});}finally{this.setData({busy:false});}}
});
