import { subscriptions,authorize,Subscription,notificationNames } from '../../services/notifications';
import { ApiError, dailyGuard, message } from '../../services/api';
import { orderingRequest, Mutation, mealNames } from '../../services/cart';
import { confirm,key } from '../../services/menu';
import { OrderDetail,selections,stateNames } from '../../services/orders';
interface Attempt { path:string; body:object; key:string|null }
Page({
 data:{subscription:null as Subscription|null,subscribing:false,subscriptionNote:'',notificationText:'',id:0,ready:false,loading:true,busy:false,error:'',order:null as OrderDetail|null,stateName:'',mealName:'',completedText:'',items:[] as ReturnType<typeof selections>,pending:[] as ReturnType<typeof selections>,actual:[] as {id:number;dishName:string;quantity:number;specText:string;sourceType:string}[],participants:'',edit:false,count:'2',remark:'',cancelReason:'',cancelForm:false,retryPending:false},
 _visible:false,_timer:0,_polling:false,_attempt:null as Attempt|null,_editVersion:0,
 onLoad(options:Record<string,string>){this.setData({id:Number(options.id)});},
 async onShow(){this._visible=true;if(!await dailyGuard()||!this._visible)return;this.setData({ready:true});void this.loadSubscription();await this.refresh();if(this._visible)this._timer=setInterval(()=>{void this.refresh();},2000);},
 async loadSubscription(){try{const rows=await subscriptions();if(this._visible)this.setData({subscription:rows.find(r=>r.event==='REVIEW_INVITED')||null});}catch{if(this._visible)this.setData({subscription:null});}},
 async subscribe(){if(this.data.subscribing||!this.data.subscription)return;this.setData({subscribing:true,subscriptionNote:''});try{const result=await authorize(this.data.subscription);if(this._visible)this.setData({subscriptionNote:result});}catch(e){if(this._visible)this.setData({subscriptionNote:message(e)});}finally{this.setData({subscribing:false});}},
 onHide(){this._visible=false;if(this._timer)clearInterval(this._timer);this._timer=0;},onUnload(){this.onHide();},
 async refresh(){if(this._polling||this.data.busy)return;this._polling=true;try{const order=await orderingRequest<OrderDetail>(`/meal-orders/${this.data.id}`);if(!this._visible)return;this.setData({order,notificationText:notificationNames[order.notificationState]||'最新进展可在这里查看。',loading:false,stateName:stateNames[order.status],completedText:order.completedAt?new Date(Date.parse(order.completedAt)+8*3600000).toISOString().slice(0,16).replace('T',' '):'',mealName:mealNames[order.meal],items:selections(order.items).map(i=>({...i,notMade:order.status==='COMPLETED'&&!order.actualItems.some(a=>a.dishId===i.dishId&&JSON.stringify(a.selections.map(s=>[s.dimensionId,s.optionId]))===JSON.stringify(i.selections.map(s=>[s.dimensionId,s.optionId])))})),pending:selections(order.pendingItems),actual:order.actualItems.map(i=>({...i,specText:i.selections.map(s=>s.dimensionName+'：'+s.optionName).join(' · ')})),participants:order.participants.map(p=>p.name+(p.initiator?'（发起人）':p.chef?'（本店主厨）':'')).join('、'),error:this.data.retryPending?this.data.error:''});}catch(e){if(this._visible)this.setData({loading:false,error:message(e)});}finally{this._polling=false;}},
 reviewMeal(){if(!this._attempt&&this.data.order?.status==='COMPLETED')wx.navigateTo({url:`/subpackages/reviews/sheet?id=${this.data.id}`});},
 confirmMeal(){if(!this._attempt&&this.data.order?.canConfirm)wx.navigateTo({url:`/pages/orders/confirm?id=${this.data.id}`});},
 modify(){if(this._attempt)return;const o=this.data.order;if(!o?.canModify)return;wx.setStorageSync('orderingTarget',{restaurantId:o.restaurantId,date:o.date,meal:o.meal});wx.switchTab({url:'/pages/ordering/index'});},
 append(){if(!this._attempt)wx.navigateTo({url:`/pages/orders/submit?id=${this.data.id}`});},
 edit(){if(this._attempt||!this.data.order?.canMeta)return;this._editVersion=this.data.order.version;this.setData({edit:true,count:String(this.data.order.dinerCount),remark:this.data.order.remark||''});},
 count(e:WechatMiniprogram.Input){if(!this.data.busy&&!this._attempt)this.setData({count:e.detail.value});},remark(e:WechatMiniprogram.Input){if(!this.data.busy&&!this._attempt)this.setData({remark:e.detail.value});},reason(e:WechatMiniprogram.Input){if(!this.data.busy&&!this._attempt)this.setData({cancelReason:e.detail.value});},
 closeEdit(){if(!this.data.busy&&!this._attempt)this.setData({edit:false});},
 async saveMeta(){if(this.data.busy||this._attempt)return;const n=Number(this.data.count);if(!Number.isInteger(n)||n<1||n>20){this.setData({error:'用餐人数为1—20'});return;}await this.perform({path:`/meal-orders/${this.data.id}/meta`,body:{version:this._editVersion,dinerCount:n,remark:this.data.remark},key:null});},
 openCancel(){if(!this._attempt&&this.data.order?.canCancel)this.setData({cancelForm:true});},
 async cancel(){if(this.data.busy||this._attempt||!this.data.order?.canCancel)return;const version=this.data.order.version,reason=this.data.cancelReason;if(!await confirm('取消整张餐单？已提交与未提交菜品会保留为历史记录。'))return;await this.perform({path:`/meal-orders/${this.data.id}/cancel`,body:{version,reason},key:key()});},
 async reopen(){if(this.data.busy||this._attempt||!this.data.order?.canReopen)return;const version=this.data.order.version;if(!await confirm('重新点餐会创建一份空清单，原取消单仍保留。'))return;await this.perform({path:`/meal-orders/${this.data.id}/reopen`,body:{version},key:key()});},
 async retry(){if(!this._attempt||this.data.busy||!await dailyGuard())return;await this.perform(this._attempt);},
 async perform(attempt:Attempt){this._attempt=attempt;this.setData({busy:true,error:''});try{if(this.data.retryPending)await orderingRequest(`/meal-orders/${this.data.id}`);const result=await orderingRequest<Mutation>(attempt.path,attempt.key?'POST':'PUT',attempt.body,attempt.key?{'Idempotency-Key':attempt.key}:{});this._attempt=null;this.setData({retryPending:false,edit:false,cancelForm:false});if(attempt.path.endsWith('/reopen')){const o=this.data.order!;wx.setStorageSync('orderingTarget',{restaurantId:o.restaurantId,date:o.date,meal:o.meal});wx.switchTab({url:'/pages/ordering/index'});return;}this.setData({busy:false});await this.refresh();}
 catch(e){const uncertain=e instanceof ApiError&&['NETWORK_ERROR','SERVICE_UNAVAILABLE','ACCESS_REQUIRED','AUTH_REQUIRED'].includes(e.code);this.setData({error:message(e),retryPending:uncertain});if(!uncertain){this._attempt=null;this.setData({busy:false});await this.refresh();this.setData({error:message(e)});if(e instanceof ApiError&&e.code==='VERSION_CONFLICT'&&this.data.edit&&this.data.order&&await confirm(`餐单已更新，最新 ${this.data.order.dinerCount} 人，备注：${this.data.order.remark||'无'}。保留当前输入，核对后再次保存？`))this._editVersion=this.data.order.version;}}
 finally{this.setData({busy:false});}},
 async recipe(e:WechatMiniprogram.TouchEvent){try{const data=await orderingRequest<{recipe:string}>(`/chef/meal-orders/${this.data.id}/items/${e.currentTarget.dataset.id}/recipe`);wx.showModal({title:'提交时做法',content:data.recipe||'主厨未填写做法',showCancel:false});}catch(e){this.setData({error:message(e)});}},
 noop(){}
});
